import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const yardLayoutTargets = [
  "yard.layoutType",
  "yard.containerWidth",
  "yard.lengthShort",
  "yard.lengthLong",
  "yard.lengthMix",
  "yard.rotation",
  "yard.stagger",
  "yard.columnGap",
  "yard.rowGap",
  "yard.randomGaps",
  "yard.containInCanvas",
  "yard.offset",
  "yard.globalScale",
  "yard.orientation",
  "yard.layout",
  "yard.radialAlign",
  "yard.colorCount",
  "yard.colorMode",
  "yard.ditherAlgorithm",
  "yard.ditherStrength",
  "yard.ditherContrast",
  "yard.matteStyle",
  "yard.matteMinCoverage",
  "yard.matteInvert",
  "yard.maskShape",
  "yard.maskScale",
  "yard.maskInset",
  "yard.seed",
  "canvas.size",
] as const;

const denseCanvasWorkloadFixture = {
  kind: "large-canvas" as const,
  loadProfile: {
    hardLimit: { height: 1080, width: 1920 },
    metric: "canvas-area" as const,
    smoothTarget: { height: 1080, width: 1920 },
    smoothTargetRatio: 1,
    target: "canvas.size",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "1920x1080 canvas is the heavy baseline before the measured control is stressed.",
  value: { height: 1080, width: 1920 },
};

const sourceMediaStressFixture = {
  kind: "media" as const,
  loadProfile: {
    hardLimit: { height: 1080, width: 1920 },
    metric: "media-area" as const,
    smoothTarget: { height: 1080, width: 1920 },
    smoothTargetRatio: 1,
    target: "media.sourceImage",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "1920x1080 is the minimum heavy media baseline for ASCII sampling.",
  value: { height: 1080, width: 1920 },
};

const narrowContainerStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 8,
    metric: "numeric-min" as const,
    smoothTarget: 8,
    smoothTargetRatio: 1,
    target: "yard.containerWidth",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Minimum container width packs the densest yard grid for preview and zoom stress.",
  value: 8,
};

const exportResolutionStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { heavyExportPreset: "8k" },
    metric: "custom" as const,
    smoothTarget: { heavyExportPreset: "8k" },
    smoothTargetRatio: 1,
    target: "export.image.resolution",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "8K is the heaviest PNG export resolution preset.",
  value: { heavyExportPreset: "8k" },
};

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["source-frame", "yard-layout", "yard-draw"],
        targets: [...yardLayoutTargets, "yard.color1", "yard.color2", "yard.color3", "yard.color4", "yard.color5", "yard.color6", "yard.color7", "yard.color8", "yard.waveAxis", "yard.waveCycles", "yard.colorPatternStep", "yard.zoneAxis", "yard.zoneCount", "yard.zone1Slot", "yard.zone2Slot", "yard.zone3Slot", "yard.zone4Slot", "yard.stripeOrientation", "yard.stripeRepeat", "yard.stripeWidth", "yard.stripeColorSlot", "yard.shadowEnabled", "yard.shadowOpacity", "yard.shadowOffsetX", "yard.shadowOffsetY", "yard.shuffle", "appearance.background", "export.includeBackground", "export.image.format", "export.image.resolution", "export.video.format", "export.video.resolution"],
      },
      {
        interaction: "control-drag",
        invalidates: ["yard-layout", "yard-draw"],
        targets: [
          "yard.rotation",
          "yard.columnGap",
          "yard.rowGap",
          "yard.stagger",
          "yard.containerWidth",
          "yard.globalScale",
          "yard.ditherStrength",
          "yard.lengthShort",
          "yard.lengthLong",
          "yard.lengthMix",
          "yard.randomGaps",
          "yard.ditherContrast",
          "yard.matteMinCoverage",
          "yard.maskScale",
          "yard.maskInset",
          "yard.colorCount",
          "yard.waveCycles",
          "yard.colorPatternStep",
          "yard.zone1Slot",
          "yard.zone2Slot",
          "yard.zone3Slot",
          "yard.zone4Slot",
          "yard.stripeRepeat",
          "yard.stripeWidth",
          "yard.stripeColorSlot",
          "yard.seed",
          "yard.shadowOpacity",
          "yard.shadowOffsetX",
          "yard.shadowOffsetY",
          "canvas.renderScale",
        ],
      },
      {
        interaction: "media-import",
        invalidates: ["source-frame", "yard-layout", "yard-draw"],
        targets: ["media.sourceImage"],
      },
      {
        interaction: "timeline-scrub",
        invalidates: ["yard-layout"],
        targets: ["timeline.keyframes", "yard.rotation", "yard.columnGap"],
      },
      {
        interaction: "timeline-playback",
        invalidates: ["yard-layout"],
        targets: ["timeline.keyframes", "timeline.playback"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["source-frame", "yard-layout", "yard-draw"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["source-frame", "yard-layout", "yard-draw"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["yard-export"],
        targets: ["export.video.resolution", "export.image.resolution", "export.video.format", "export.image.format"],
      },
      {
        interaction: "animation-frame",
        invalidates: ["yard-layout"],
        targets: ["timeline.playback"],
      },
    ],
    passes: [
      {
        cacheKey: ["media.sourceImage", "canvas.size", "timeline.currentTimeSeconds"],
        id: "source-frame",
        inputs: ["media.sourceImage", "canvas.size", "timeline.currentTimeSeconds"],
        invalidatedBy: ["media.sourceImage", "canvas.size", "timeline.currentTimeSeconds"],
        kind: "decode",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [...yardLayoutTargets, "source-frame"],
        id: "yard-layout",
        inputs: [...yardLayoutTargets, "source-frame"],
        invalidatedBy: [...yardLayoutTargets, "source-frame"],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["yard-layout", "appearance.background", "export.includeBackground", "canvas.renderScale"],
        id: "yard-draw",
        inputs: ["yard-layout", "appearance.background", "export.includeBackground", "canvas.renderScale"],
        invalidatedBy: ["yard-layout", "appearance.background", "export.includeBackground", "canvas.renderScale"],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "yard-layout",
          "export.video.format",
          "export.video.resolution",
          "export.includeBackground",
        ],
        id: "yard-export",
        inputs: [
          "yard-layout",
          "export.video.format",
          "export.video.resolution",
          "export.includeBackground",
        ],
        invalidatedBy: [
          "yard-layout",
          "export.video.format",
          "export.video.resolution",
          "export.includeBackground",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Video seeking during export may soft-seek on some browsers.",
      "Alpha WebM support varies; MOV ProRes path loads ffmpeg.wasm lazily.",
    ],
    layers: [
      {
        content: ["geometry", "dense-pattern"],
        exportMode: "included",
        id: "container-yard-foreground",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-product-canvas]",
      },
    ],
    measuredAlternativeEvidence: [
      {
        alternativeStrategy: "webgl",
        decision:
          "Keep Canvas 2D for SVG export parity, simpler alpha video frame readback, and batched rectangle fills that stay under preview-render budgets on dense yards.",
        fixture: "1920x1080 yard at minimum container width with ASCII source loaded",
        measuredResult:
          "A WebGL instanced-rect prototype exceeded preview-render maxLongTaskMs on dense ASCII grids while Canvas 2D batched fills remained under budget.",
        scenarioId: "preview-render",
      },
    ],
    performanceRisks: [
      "Dense grids plus per-frame video decode are main-thread Canvas 2D workloads.",
      "Keyframe scrubbing rebuilds slots and color assignment each sample.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "pixel",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "Container rectangles and palette assignment are Canvas-friendly; WebGL would add complexity without matching vector SVG export needs.",
      "SVG still export and alpha PNG stills stay aligned with Canvas 2D draw paths.",
      "text-output and vector-output rendererWorkload alternatives were rejected because ASCII block sampling is fundamentally pixel-output work on Canvas 2D.",
      "exportRenderer canvas-2d preserves product-quality PNG/SVG export/copy behavior without a separate GPU export path.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: preview render stays under budget",
      budget: { maxLongTaskMs: 50, maxPreviewMs: 2000, maxRenderMs: 2000 },
      expectedObservable: "Worst-case preview at minimum container width stays under budget.",
      fixture: "1920x1080 dense yard",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      workload: false,
      stressFixture: narrowContainerStressFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport stays stable",
      browser: true,
      browserTestName: "browser perf: viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Panning/zooming the canvas keeps the viewport stable without relayout jumps.",
      fixture: "default container yard",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport zoom stays stable under load",
      browser: true,
      browserTestName: "browser perf: viewport zoom stays stable under load",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      expectedObservable: "Toolbar zoom stays smooth on a dense yard.",
      fixture: "dense yard under zoom stress",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      workload: false,
      stressFixture: narrowContainerStressFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: export png stays under budget",
      browser: true,
      browserTestName: "browser perf: export png stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Export PNG completes within the export budget.",
      fixture: "1920x1080 yard export",
      id: "export-copy",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: keyframe viewport stays stable",
      browser: true,
      browserTestName: "browser perf: keyframe viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Zoom/radar, expanded keyframes, diamond creation, and scrub/playback keep the canvas viewport stable.",
      fixture: "yard with keyframed rotation",
      id: "timeline-keyframes-viewport",
      interaction: "viewport-stability",
      target: "timeline.keyframes",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: animation frame during playback",
      browser: true,
      browserTestName: "browser perf: animation frame during playback",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 50 },
      expectedObservable: "Timeline playback advances layout frames without long tasks.",
      fixture: "playing yard timeline",
      id: "animation-frame",
      interaction: "animation-frame",
      stress: true,
      target: "timeline.playback",
      workload: false,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "yard.stagger",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Staggered layout during playback increases per-frame work.",
        value: 100,
      },
    },
    {
      automated: true,
      automatedTestName: "perf: animation viewport drag stays smooth",
      browser: true,
      browserTestName: "browser perf: animation viewport drag stays smooth",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      uiSelector: "[role=\"application\"][aria-label=\"Canvas viewport\"]",
      expectedObservable: "Dragging the canvas viewport during playback stays smooth.",
      fixture: "playing yard during canvas pan",
      id: "animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      target: "canvas.viewport",
      workload: false,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "yard.stagger",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Full stagger during playback increases per-frame layout work while dragging the viewport.",
        value: 100,
      },
    },
    {
      automated: true,
      automatedTestName: "perf: stagger drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stagger drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Stagger",
      expectedObservable: "Dragging Stagger updates brick-bond offset with live feedback.",
      fixture: "default yard",
      id: "yard-stagger-drag",
      interaction: "control-drag",
      target: "yard.stagger",
      values: { default: 0, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: rotation drag stays responsive",
      browser: true,
      browserTestName: "browser perf: rotation drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Rotation",
      expectedObservable: "Dragging Rotation rebuilds the yard without freezing the UI.",
      fixture: "dense yard",
      id: "yard-rotation-drag",
      interaction: "control-drag",
      target: "yard.rotation",
      values: { default: 0, max: 180, min: -180 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: container width drag stays responsive",
      browser: true,
      browserTestName: "browser perf: container width drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Width",
      expectedObservable: "Dragging Width at stress values rebuilds slot density responsively.",
      fixture: "large canvas yard",
      id: "yard-width-drag",
      interaction: "control-drag",
      stress: true,
      target: "yard.containerWidth",
      values: { default: 28, max: 80, min: 8 },
      workload: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 8,
          metric: "numeric-min",
          smoothTarget: 8,
          smoothTargetRatio: 1,
          target: "yard.containerWidth",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Minimum width packs the densest container grid.",
        value: 8,
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: orientation change stays responsive",
      browser: true,
      browserTestName: "browser perf: orientation change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Orientation",
      expectedObservable: "Switching Orientation swaps container axes within budget.",
      fixture: "default yard",
      id: "yard-orientation-change",
      interaction: "control-change",
      target: "yard.orientation",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: layout change stays responsive",
      browser: true,
      browserTestName: "browser perf: layout change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Stagger axis",
      expectedObservable: "Switching stagger axis updates layout within budget.",
      fixture: "rectangular yard",
      id: "yard-layout-change",
      interaction: "control-change",
      target: "yard.layout",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: layout type change stays responsive",
      browser: true,
      browserTestName: "browser perf: layout type change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "App mode",
      expectedObservable: "Switching app mode rebuilds layout within budget.",
      fixture: "default yard",
      id: "yard-layout-type-change",
      interaction: "control-change",
      target: "yard.layoutType",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: radial align change stays responsive",
      browser: true,
      browserTestName: "browser perf: radial align change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Ring align",
      expectedObservable: "Switching ring align updates radial orientation within budget.",
      fixture: "radial yard",
      id: "yard-radial-align-change",
      interaction: "control-change",
      target: "yard.radialAlign",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: source image import stays responsive",
      browser: true,
      browserTestName: "browser perf: source image import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      controlLabel: "Source",
      expectedObservable: "Importing 1920x1080 source media prepares ASCII sampling without freezing.",
      fixture: "ASCII mode yard",
      id: "media-source-image-import",
      interaction: "media-import",
      stress: true,
      target: "media.sourceImage",
      workload: true,
      stressFixture: sourceMediaStressFixture,
      workloadFixture: sourceMediaStressFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: dither app mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: dither app mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "App mode",
      expectedObservable: "Leaving ASCII mode after import stays responsive.",
      fixture: "ASCII yard with source",
      id: "yard-dither-enabled-change",
      interaction: "control-change",
      target: "yard.layoutType",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: dither algorithm change stays responsive",
      browser: true,
      browserTestName: "browser perf: dither algorithm change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Style",
      expectedObservable: "Switching dither style remaps blocks within budget.",
      fixture: "ASCII yard with source",
      id: "yard-dither-algorithm-change",
      interaction: "control-change",
      target: "yard.ditherAlgorithm",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: dither strength drag stays responsive",
      browser: true,
      browserTestName: "browser perf: dither strength drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Image Mix",
      expectedObservable: "Dragging Image Mix blends sampled colors with live feedback.",
      fixture: "ASCII yard on large canvas",
      id: "yard-dither-strength-drag",
      interaction: "control-drag",
      stress: true,
      target: "yard.ditherStrength",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "yard.ditherStrength",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Full image mix maximizes sampled block work.",
        value: 100,
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: dither contrast drag stays responsive",
      browser: true,
      browserTestName: "browser perf: dither contrast drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Image Contrast",
      expectedObservable: "Dragging Image Contrast adjusts sampling contrast live.",
      fixture: "ASCII yard with source",
      id: "yard-dither-contrast-drag",
      interaction: "control-drag",
      target: "yard.ditherContrast",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: matte style change stays responsive",
      browser: true,
      browserTestName: "browser perf: matte style change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Subject matte",
      expectedObservable: "Switching subject matte refilters blocks within budget.",
      fixture: "ASCII yard with source",
      id: "yard-matte-style-change",
      interaction: "control-change",
      target: "yard.matteStyle",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: matte min coverage drag stays responsive",
      browser: true,
      browserTestName: "browser perf: matte min coverage drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Min coverage",
      expectedObservable: "Dragging Min coverage refilters block placement live.",
      fixture: "ASCII yard with source",
      id: "yard-matte-min-coverage-drag",
      interaction: "control-drag",
      target: "yard.matteMinCoverage",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: matte invert change stays responsive",
      browser: true,
      browserTestName: "browser perf: matte invert change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Invert",
      expectedObservable: "Toggling Invert flips subject vs empty matte regions within budget.",
      fixture: "ASCII yard with source",
      id: "yard-matte-invert-change",
      interaction: "control-change",
      target: "yard.matteInvert",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: length short drag stays responsive",
      browser: true,
      browserTestName: "browser perf: length short drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Length short",
      expectedObservable: "Dragging Length short updates short containers live.",
      fixture: "default yard",
      id: "yard-length-short-drag",
      interaction: "control-drag",
      target: "yard.lengthShort",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: length long drag stays responsive",
      browser: true,
      browserTestName: "browser perf: length long drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Length long",
      expectedObservable: "Dragging Length long updates long containers live.",
      fixture: "default yard",
      id: "yard-length-long-drag",
      interaction: "control-drag",
      target: "yard.lengthLong",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: length mix drag stays responsive",
      browser: true,
      browserTestName: "browser perf: length mix drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Long mix",
      expectedObservable: "Dragging Long mix varies 20ft/40ft mix live.",
      fixture: "default yard",
      id: "yard-length-mix-drag",
      interaction: "control-drag",
      target: "yard.lengthMix",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: column gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: column gap drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Column gap",
      expectedObservable: "Dragging Column gap updates spacing without long tasks.",
      fixture: "dense yard",
      id: "yard-column-gap-drag",
      interaction: "control-drag",
      target: "yard.columnGap",
      values: { default: 3, max: 40, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: row gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: row gap drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Row gap",
      expectedObservable: "Dragging Row gap updates vertical spacing live.",
      fixture: "default yard",
      id: "yard-row-gap-drag",
      interaction: "control-drag",
      target: "yard.rowGap",
      values: { default: 3, max: 40, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: gaps drag stays responsive",
      browser: true,
      browserTestName: "browser perf: gaps drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Gaps",
      expectedObservable: "Dragging Gaps skips more slots with live feedback.",
      fixture: "default yard",
      id: "yard-random-gaps-drag",
      interaction: "control-drag",
      target: "yard.randomGaps",
      values: { default: 8, max: 60, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: offset drag stays responsive",
      browser: true,
      browserTestName: "browser perf: offset drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Offset",
      expectedObservable: "Dragging Offset translates the pattern live.",
      fixture: "default yard",
      id: "yard-offset-drag",
      interaction: "control-drag",
      target: "yard.offset",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: global scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: global scale drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Global scale",
      expectedObservable: "Dragging Global scale rescales geometry with live feedback.",
      fixture: "default yard",
      id: "yard-global-scale-drag",
      interaction: "control-drag",
      stress: true,
      target: "yard.globalScale",
      values: { default: 100, max: 200, min: 25 },
      workload: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 25,
          metric: "numeric-min",
          smoothTarget: 25,
          smoothTargetRatio: 1,
          target: "yard.globalScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Minimum global scale packs the densest geometry.",
        value: 25,
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: contain toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: contain toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Contain",
      expectedObservable: "Toggling Contain filters edge slots within budget.",
      fixture: "default yard",
      id: "yard-contain-change",
      interaction: "control-change",
      target: "yard.containInCanvas",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: color count drag stays responsive",
      browser: true,
      browserTestName: "browser perf: color count drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Colors",
      expectedObservable: "Dragging Colors activates more palette slots live.",
      fixture: "default yard",
      id: "yard-color-count-drag",
      interaction: "control-drag",
      target: "yard.colorCount",
      values: { default: 4, max: 8, min: 1 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: color mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: color mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color mode",
      expectedObservable: "Switching color mode reassigns palette spatially within budget.",
      fixture: "default yard",
      id: "yard-color-mode-change",
      interaction: "control-change",
      target: "yard.colorMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: wave cycles drag stays responsive",
      browser: true,
      browserTestName: "browser perf: wave cycles drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Wave cycles",
      expectedObservable: "Dragging Wave cycles increases palette repetition live.",
      fixture: "wave color mode",
      id: "yard-wave-cycles-drag",
      interaction: "control-drag",
      target: "yard.waveCycles",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: pattern step drag stays responsive",
      browser: true,
      browserTestName: "browser perf: pattern step drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Pattern step",
      expectedObservable: "Dragging Pattern step changes spatial frequency live.",
      fixture: "checker color mode",
      id: "yard-color-pattern-step-drag",
      interaction: "control-drag",
      target: "yard.colorPatternStep",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: wave axis change stays responsive",
      browser: true,
      browserTestName: "browser perf: wave axis change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Wave axis",
      expectedObservable: "Switching Wave axis reorients the gradient within budget.",
      fixture: "wave color mode",
      id: "yard-wave-axis-change",
      interaction: "control-change",
      target: "yard.waveAxis",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone axis change stays responsive",
      browser: true,
      browserTestName: "browser perf: zone axis change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Zone axis",
      expectedObservable: "Switching Zone axis reorients brand zones within budget.",
      fixture: "zones color mode",
      id: "yard-zone-axis-change",
      interaction: "control-change",
      target: "yard.zoneAxis",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone count change stays responsive",
      browser: true,
      browserTestName: "browser perf: zone count change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Zone count",
      expectedObservable: "Changing Zone count splits regions within budget.",
      fixture: "zones color mode",
      id: "yard-zone-count-change",
      interaction: "control-change",
      target: "yard.zoneCount",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone 1 slot drag stays responsive",
      browser: true,
      browserTestName: "browser perf: zone 1 slot drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Zone 1",
      expectedObservable: "Dragging Zone 1 remaps palette slot live.",
      fixture: "zones color mode",
      id: "yard-zone1-slot-drag",
      interaction: "control-drag",
      target: "yard.zone1Slot",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone 2 slot drag stays responsive",
      browser: true,
      browserTestName: "browser perf: zone 2 slot drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Zone 2",
      expectedObservable: "Dragging Zone 2 remaps palette slot live.",
      fixture: "zones color mode",
      id: "yard-zone2-slot-drag",
      interaction: "control-drag",
      target: "yard.zone2Slot",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone 3 slot drag stays responsive",
      browser: true,
      browserTestName: "browser perf: zone 3 slot drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Zone 3",
      expectedObservable: "Dragging Zone 3 remaps palette slot live.",
      fixture: "zones color mode",
      id: "yard-zone3-slot-drag",
      interaction: "control-drag",
      target: "yard.zone3Slot",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone 4 slot drag stays responsive",
      browser: true,
      browserTestName: "browser perf: zone 4 slot drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Zone 4",
      expectedObservable: "Dragging Zone 4 remaps palette slot live.",
      fixture: "zones color mode",
      id: "yard-zone4-slot-drag",
      interaction: "control-drag",
      target: "yard.zone4Slot",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stripe orientation change stays responsive",
      browser: true,
      browserTestName: "browser perf: stripe orientation change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Stripe axis",
      expectedObservable: "Switching Stripe axis rotates highlight bands within budget.",
      fixture: "stripes color mode",
      id: "yard-stripe-orientation-change",
      interaction: "control-change",
      target: "yard.stripeOrientation",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stripe repeat drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stripe repeat drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Stripe count",
      expectedObservable: "Dragging Stripe count increases band density live.",
      fixture: "stripes color mode",
      id: "yard-stripe-repeat-drag",
      interaction: "control-drag",
      target: "yard.stripeRepeat",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stripe width drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stripe width drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Stripe width",
      expectedObservable: "Dragging Stripe width widens highlight bands live.",
      fixture: "stripes color mode",
      id: "yard-stripe-width-drag",
      interaction: "control-drag",
      target: "yard.stripeWidth",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stripe color slot drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stripe color slot drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Highlight",
      expectedObservable: "Dragging Highlight changes stripe palette slot live.",
      fixture: "stripes color mode",
      id: "yard-stripe-color-slot-drag",
      interaction: "control-drag",
      target: "yard.stripeColorSlot",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: shuffle action stays responsive",
      browser: true,
      browserTestName: "browser perf: shuffle action stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Shuffle",
      expectedObservable: "Clicking Shuffle advances seed and gaps within budget.",
      fixture: "default yard",
      id: "yard-shuffle-action",
      interaction: "control-change",
      target: "yard.shuffle",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 1 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 1 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 1 repaints mapped containers within budget.",
      fixture: "default yard",
      id: "yard-color1-change",
      interaction: "control-change",
      target: "yard.color1",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 2 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 2 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 2 repaints mapped containers within budget.",
      fixture: "default yard",
      id: "yard-color2-change",
      interaction: "control-change",
      target: "yard.color2",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 3 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 3 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 3 repaints mapped containers within budget.",
      fixture: "six-color yard",
      id: "yard-color3-change",
      interaction: "control-change",
      target: "yard.color3",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 4 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 4 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 4 repaints mapped containers within budget.",
      fixture: "six-color yard",
      id: "yard-color4-change",
      interaction: "control-change",
      target: "yard.color4",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 5 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 5 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 5 repaints mapped containers within budget.",
      fixture: "six-color yard",
      id: "yard-color5-change",
      interaction: "control-change",
      target: "yard.color5",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 6 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 6 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 6 repaints mapped containers within budget.",
      fixture: "six-color yard",
      id: "yard-color6-change",
      interaction: "control-change",
      target: "yard.color6",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 7 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 7 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 7 repaints mapped containers within budget.",
      fixture: "seven-color yard",
      id: "yard-color7-change",
      interaction: "control-change",
      target: "yard.color7",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color 8 change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color 8 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Container Colors",
      expectedObservable: "Changing palette color 8 repaints mapped containers within budget.",
      fixture: "eight-color yard",
      id: "yard-color8-change",
      interaction: "control-change",
      target: "yard.color8",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: shadow toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: shadow toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Shadow",
      expectedObservable: "Toggling Shadow adds or removes drop shadows within budget.",
      fixture: "default yard",
      id: "yard-shadow-enabled-change",
      interaction: "control-change",
      target: "yard.shadowEnabled",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: shadow opacity drag stays responsive",
      browser: true,
      browserTestName: "browser perf: shadow opacity drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Shadow opacity",
      expectedObservable: "Dragging Shadow opacity adjusts darkness live.",
      fixture: "shadows enabled",
      id: "yard-shadow-opacity-drag",
      interaction: "control-drag",
      target: "yard.shadowOpacity",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: shadow x drag stays responsive",
      browser: true,
      browserTestName: "browser perf: shadow x drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Shadow X",
      expectedObservable: "Dragging Shadow X offsets shadows horizontally live.",
      fixture: "shadows enabled",
      id: "yard-shadow-offset-x-drag",
      interaction: "control-drag",
      target: "yard.shadowOffsetX",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: shadow y drag stays responsive",
      browser: true,
      browserTestName: "browser perf: shadow y drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Shadow Y",
      expectedObservable: "Dragging Shadow Y offsets shadows vertically live.",
      fixture: "shadows enabled",
      id: "yard-shadow-offset-y-drag",
      interaction: "control-drag",
      target: "yard.shadowOffsetY",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: include background change stays responsive",
      browser: true,
      browserTestName: "browser perf: include background change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable: "Toggling Include shows or hides product background within budget.",
      fixture: "default yard",
      id: "export-include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Background",
      expectedObservable: "Changing background color repaints preview within budget.",
      fixture: "default yard",
      id: "appearance-background-change",
      interaction: "control-change",
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image format change stays responsive",
      browser: true,
      browserTestName: "browser perf: image format change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Switching image export format stays responsive.",
      fixture: "default yard",
      id: "export-image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image resolution change stays responsive",
      browser: true,
      browserTestName: "browser perf: image resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Preset",
      expectedObservable: "Selecting 8K export preset stays responsive.",
      fixture: "large canvas yard",
      id: "export-image-resolution-change",
      interaction: "control-change",
      stress: true,
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      stressFixture: exportResolutionStressFixture,
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: video format change stays responsive",
      browser: true,
      browserTestName: "browser perf: video format change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Switching video export format stays responsive.",
      fixture: "animated yard",
      id: "export-video-format-change",
      interaction: "control-change",
      target: "export.video.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: video resolution change stays responsive",
      browser: true,
      browserTestName: "browser perf: video resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Preset",
      expectedObservable: "Selecting 4K video export preset stays responsive.",
      fixture: "animated yard",
      id: "export-video-resolution-change",
      interaction: "control-change",
      target: "export.video.resolution",
      values: { default: "current", max: "4k", min: "current" },
      workload: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { resolution: "4k" },
          metric: "custom",
          smoothTarget: { resolution: "4k" },
          smoothTargetRatio: 1,
          target: "export.video.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the heaviest video export resolution preset.",
        value: { resolution: "4k" },
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: mask shape change stays responsive",
      browser: true,
      browserTestName: "browser perf: mask shape change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Shape",
      expectedObservable: "Switching mask shape reclips containers within budget.",
      fixture: "default yard",
      id: "yard-mask-shape-change",
      interaction: "control-change",
      target: "yard.maskShape",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: mask fill area drag stays responsive",
      browser: true,
      browserTestName: "browser perf: mask fill area drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Fill area",
      expectedObservable: "Dragging Fill area rescales the clip boundary live.",
      fixture: "circle mask yard",
      id: "yard-mask-scale-drag",
      interaction: "control-drag",
      stress: true,
      target: "yard.maskScale",
      values: { default: 92, max: 100, min: 20 },
      workload: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "yard.maskScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum fill area scales mask geometry across the canvas.",
        value: 100,
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: mask inset drag stays responsive",
      browser: true,
      browserTestName: "browser perf: mask inset drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Inset",
      expectedObservable: "Dragging Inset shrinks the clip boundary live.",
      fixture: "circle mask yard",
      id: "yard-mask-inset-drag",
      interaction: "control-drag",
      target: "yard.maskInset",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: seed drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Seed",
      expectedObservable: "Dragging Seed reshuffles palette assignment live.",
      fixture: "default yard",
      id: "yard-seed-drag",
      interaction: "control-drag",
      target: "yard.seed",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: render scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: render scale drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 50 },
      controlLabel: "Resolution scale",
      expectedObservable: "Dragging Resolution scale doubles backing pixels with live preview.",
      fixture: "default yard",
      id: "canvas-render-scale-drag",
      interaction: "control-drag",
      stress: true,
      target: "canvas.renderScale",
      values: { default: 1, max: 2, min: 1 },
      workload: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 2,
          metric: "numeric-max",
          smoothTarget: 2,
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Render scale 2 doubles backing pixels for Canvas 2D preview.",
        value: 2,
      },
      workloadFixture: denseCanvasWorkloadFixture,
    },  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "yard.containerWidth",
    "yard.ditherStrength",
    "yard.globalScale",
    "yard.maskScale",
    "canvas.renderScale",
    "export.image.resolution",
    "export.video.resolution",
  ],
});
