import { defineToolcraft } from "@/toolcraft/runtime";

import { DEFAULT_CONTAINER_COLORS } from "./container-yard-math";

/**
 * Container Yard — bird's-eye container stack pattern generator. Procedural
 * rectangle grids with stagger, rotation, palette randomization, and SVG/PNG export.
 */
export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: true,
  },
  export: {
    png: {
      background: "include",
    },
  },
  persistence: {
    include: ["values", "canvas", "panels", "media", "timeline"],
    key: "toolcraft:container-yard:state:v4",
    storage: "localStorage",
    version: 4,
  },
  panels: {
    timeline: {
      defaultDurationSeconds: 4,
      enabled: true,
      mode: "keyframes",
    },
    controls: {
      title: "Controls",
      sections: [
        {
          controls: {
            layoutType: {
              defaultValue: "rectangular",
              label: "App mode",
              options: [
                { label: "Rectangular", value: "rectangular" },
                { label: "Radial", value: "radial" },
                { label: "ASCII", value: "dither" },
              ],
              orderRole: "mode",
              performanceReason: "Switches the whole app between grid, ring, and image ASCII modes.",
              performanceRole: "responsiveness",
              target: "yard.layoutType",
              type: "select",
            },
            radialAlign: {
              defaultValue: "tangent",
              description: "Tangent follows the ring curve; Radial points toward the center.",
              label: "Ring align",
              options: [
                { label: "Tangent", value: "tangent" },
                { label: "Radial", value: "radial" },
              ],
              orderRole: "mode",
              performanceReason: "Rotates containers to follow ring curvature or spokes.",
              performanceRole: "responsiveness",
              target: "yard.radialAlign",
              type: "select",
              visibleWhen: { equals: "radial", target: "yard.layoutType" },
            },
            layout: {
              defaultValue: "rows",
              description: "Rows stagger horizontally; columns stagger vertically.",
              label: "Stagger axis",
              options: [
                { label: "Rows", value: "rows" },
                { label: "Columns", value: "columns" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses which grid axis receives brick-bond offset.",
              performanceRole: "responsiveness",
              target: "yard.layout",
              type: "select",
              visibleWhen: { equals: "rectangular", target: "yard.layoutType" },
            },
            orientation: {
              defaultValue: "vertical",
              label: "Orientation",
              options: [
                { label: "Vertical", value: "vertical" },
                { label: "Horizontal", value: "horizontal" },
              ],
              orderRole: "mode",
              performanceReason: "Swaps container width and length axes.",
              performanceRole: "responsiveness",
              target: "yard.orientation",
              type: "select",
            },
            ditherAlgorithm: {
              defaultValue: "palette",
              description: "Palette quantizes sampled image blocks to Container Colors; Blocks uses raw image color; Halftone and Mono add stylized tone mapping.",
              label: "Style",
              options: [
                { label: "Blocks", value: "blocks" },
                { label: "Palette", value: "palette" },
                { label: "Halftone", value: "halftone" },
                { label: "Mono", value: "mono" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses how sampled image colors map into container blocks.",
              performanceRole: "responsiveness",
              target: "yard.ditherAlgorithm",
              type: "select",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
            ditherStrength: {
              defaultValue: 0,
              description:
                "Blend Color Pattern with sampled still-image colors only when Subject matte is Off. Video and silhouettes always keep grid colors; the source only cuts which cells show.",
              label: "Image Mix",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Mixes sampled image blocks with color-mode output.",
              performanceRole: "workload",
              step: 1,
              target: "yard.ditherStrength",
              type: "slider",
              unit: "%",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
            ditherContrast: {
              defaultValue: 0,
              label: "Image Contrast",
              max: 100,
              min: -100,
              orderRole: "strength",
              performanceReason: "Adjusts sampled image contrast before block mapping.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.ditherContrast",
              type: "slider",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
            matteStyle: {
              defaultValue: "both",
              description:
                "Skip blocks over transparent pixels and flat empty zones (including white/black holes inside silhouettes). Off keeps the full ASCII grid.",
              label: "Subject matte",
              options: [
                { label: "Both", value: "both" },
                { label: "Alpha", value: "alpha" },
                { label: "Auto", value: "auto" },
                { label: "Off", value: "off" },
              ],
              orderRole: "detail",
              performanceReason: "Chooses how subject pixels are detected before ASCII block placement.",
              performanceRole: "responsiveness",
              target: "yard.matteStyle",
              type: "select",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
            matteMinCoverage: {
              defaultValue: 40,
              description:
                "Minimum share of subject pixels required inside a block for it to render. Raise to clear more empty fringe around silhouettes.",
              label: "Min coverage",
              max: 100,
              min: 0,
              orderRole: "detail",
              performanceReason: "Filters blocks that only graze transparent or background regions.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.matteMinCoverage",
              type: "slider",
              unit: "%",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
            matteInvert: {
              defaultValue: false,
              description:
                "Flip subject vs empty in the same matte. Use for white-on-black sources when the default cutout is inverted.",
              label: "Invert mask",
              orderRole: "detail",
              performanceReason: "Toggles matte polarity without rebuilding sampling strategy.",
              performanceRole: "responsiveness",
              target: "yard.matteInvert",
              type: "switch",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["layoutType", "radialAlign"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["orientation", "layout"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["ditherAlgorithm", "ditherStrength"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["ditherContrast", "matteStyle"],
              layout: "inline",
            },
          ],
          title: "App Mode",
        },
        {
          controls: {
            sourceImage: {
              accept: "image/*,video/*",
              assetKind: "image",
              defaultValue: null,
              description: "Still image or video that drives ASCII block sampling at the playhead.",
              label: false,
              orderRole: "input",
              performanceReason: "Uploads a reference image or video for ASCII block sampling.",
              performanceRole: "responsiveness",
              target: "media.sourceImage",
              type: "fileDrop",
              visibleWhen: { equals: "dither", target: "yard.layoutType" },
            },
          },
          title: "Source",
        },
        {
          controls: {
            containerWidth: {
              defaultValue: 28,
              label: "Width",
              max: 80,
              min: 8,
              orderRole: "primary",
              performanceReason: "Narrow container face width.",
              performanceRole: "workload",
              step: 1,
              target: "yard.containerWidth",
              type: "slider",
              unit: "px",
            },
            lengthShort: {
              defaultValue: 72,
              description: "Container length along the grid axis.",
              label: "Length",
              max: 200,
              min: 24,
              orderRole: "primary",
              performanceReason: "Container length in the grid.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.lengthShort",
              type: "slider",
              unit: "px",
            },
            globalScale: {
              defaultValue: 100,
              description:
                "Scales container width, length, and gaps together to make the pattern denser or larger on the same canvas.",
              label: "Global scale",
              max: 200,
              min: 25,
              orderRole: "spatial",
              performanceReason: "Uniformly scales container geometry and spacing.",
              performanceRole: "workload",
              step: 1,
              target: "yard.globalScale",
              type: "slider",
              unit: "%",
            },
            rotation: {
              defaultValue: 0,
              label: "Rotation",
              max: 180,
              min: -180,
              orderRole: "spatial",
              performanceReason: "Rotates the entire container grid.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.rotation",
              type: "slider",
              unit: "°",
            },
            stagger: {
              defaultValue: 0,
              description: "Brick-bond offset for alternating rows or columns.",
              label: "Stagger",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Shifts every other row/column for jagged rhythm.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.stagger",
              type: "slider",
              unit: "%",
            },
            columnGap: {
              defaultValue: 3,
              label: "Column gap",
              max: 40,
              min: 0,
              orderRole: "detail",
              performanceReason: "Horizontal spacing between container columns.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.columnGap",
              type: "slider",
              unit: "px",
            },
            rowGap: {
              defaultValue: 3,
              label: "Row gap",
              max: 40,
              min: 0,
              orderRole: "detail",
              performanceReason: "Vertical spacing between container rows.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.rowGap",
              type: "slider",
              unit: "px",
            },
            randomGaps: {
              defaultValue: 8,
              description: "Random empty slots for yard realism.",
              label: "Gaps",
              max: 60,
              min: 0,
              orderRole: "detail",
              performanceReason: "Skips grid cells using the color seed.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.randomGaps",
              type: "slider",
              unit: "%",
            },
            containInCanvas: {
              defaultValue: false,
              description:
                "On: only place containers fully inside the canvas. Off: containers may extend to the edges and clip.",
              label: "Contain",
              orderRole: "detail",
              performanceReason: "Filters grid slots to fully inside canvas bounds.",
              performanceRole: "responsiveness",
              target: "yard.containInCanvas",
              type: "switch",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["containerWidth", "lengthShort"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["columnGap", "rowGap"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["stagger", "randomGaps"],
              layout: "inline",
            },
          ],
          title: "Grid Layout",
        },
        {
          controls: {
            offset: {
              defaultValue: { x: 0, y: 0 },
              description: "Pan the pattern within the canvas or mask.",
              label: "Offset",
              orderRole: "spatial",
              performanceReason: "Translates the generated grid.",
              performanceRole: "responsiveness",
              target: "yard.offset",
              type: "vector",
              variant: "spatial",
              xLabel: "X",
              yLabel: "Y",
            },
          },
          title: "Pattern Position",
        },
        {
          controls: {
            colorCount: {
              defaultValue: 4,
              label: "Colors",
              max: 8,
              min: 1,
              orderRole: "mode",
              performanceReason: "Number of active palette slots.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.colorCount",
              type: "slider",
            },
            color1: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[0] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 1.",
              performanceRole: "responsiveness",
              target: "yard.color1",
              type: "color",
            },
            color2: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[1] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 2.",
              performanceRole: "responsiveness",
              target: "yard.color2",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 2, target: "yard.colorCount" },
            },
            color3: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[2] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 3.",
              performanceRole: "responsiveness",
              target: "yard.color3",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 3, target: "yard.colorCount" },
            },
            color4: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[3] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 4.",
              performanceRole: "responsiveness",
              target: "yard.color4",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 4, target: "yard.colorCount" },
            },
            color5: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[4] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 5.",
              performanceRole: "responsiveness",
              target: "yard.color5",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 5, target: "yard.colorCount" },
            },
            color6: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[5] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 6.",
              performanceRole: "responsiveness",
              target: "yard.color6",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 6, target: "yard.colorCount" },
            },
            color7: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[6] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 7.",
              performanceRole: "responsiveness",
              target: "yard.color7",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 7, target: "yard.colorCount" },
            },
            color8: {
              defaultValue: { hex: DEFAULT_CONTAINER_COLORS[7] },
              label: false,
              orderRole: "color",
              performanceReason: "Palette slot 8.",
              performanceRole: "responsiveness",
              target: "yard.color8",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 8, target: "yard.colorCount" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["colorCount"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["color1", "color2"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["color3", "color4"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["color5", "color6"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["color7", "color8"],
              layout: "inline",
            },
          ],
          title: "Container Colors",
        },
        {
          controls: {
            colorMode: {
              defaultValue: "random",
              description:
                "Spatial modes assign palette colors by grid position, region, or procedural pattern.",
              label: "Color mode",
              options: [
                { label: "Random", value: "random" },
                { label: "Wave", value: "wave" },
                { label: "Zones", value: "zones" },
                { label: "Stripes", value: "stripes" },
                { label: "Checker", value: "checker" },
                { label: "Quadrants", value: "quadrants" },
                { label: "Rings", value: "rings" },
                { label: "Clusters", value: "clusters" },
                { label: "Chevron", value: "chevron" },
              ],
              orderRole: "mode",
              performanceReason: "Switches between random and spatial color assignment.",
              performanceRole: "responsiveness",
              target: "yard.colorMode",
              type: "select",
            },
            waveAxis: {
              defaultValue: "column",
              description: "Row shifts by Y, Column by X, Radial by distance from center.",
              label: "Wave axis",
              options: [
                { label: "Row", value: "row" },
                { label: "Column", value: "column" },
                { label: "Radial", value: "radial" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses the wave gradient direction.",
              performanceRole: "responsiveness",
              target: "yard.waveAxis",
              type: "select",
              visibleWhen: { equals: "wave", target: "yard.colorMode" },
            },
            waveCycles: {
              defaultValue: 3,
              description: "How many palette cycles repeat across the wave axis.",
              label: "Wave cycles",
              max: 8,
              min: 1,
              orderRole: "strength",
              performanceReason: "Increases palette repetition frequency.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.waveCycles",
              type: "slider",
              visibleWhen: { equals: "wave", target: "yard.colorMode" },
            },
            colorPatternStep: {
              defaultValue: 4,
              description:
                "Checker cell size, ring count, cluster size, or chevron frequency depending on mode.",
              label: "Pattern step",
              max: 16,
              min: 1,
              orderRole: "strength",
              performanceReason: "Adjusts spatial frequency for checker, ring, cluster, and chevron modes.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.colorPatternStep",
              type: "slider",
              visibleWhen: {
                oneOf: ["checker", "rings", "clusters", "chevron"],
                target: "yard.colorMode",
              },
            },
          },
          title: "Color Pattern",
        },
        {
          controls: {
            zoneAxis: {
              defaultValue: "horizontal",
              description: "Horizontal splits left-to-right; vertical splits top-to-bottom.",
              label: "Zone axis",
              options: [
                { label: "Horizontal", value: "horizontal" },
                { label: "Vertical", value: "vertical" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses brand zone orientation.",
              performanceRole: "responsiveness",
              target: "yard.zoneAxis",
              type: "select",
            },
            zoneCount: {
              defaultValue: "2",
              label: "Zone count",
              options: [
                { label: "2 zones", value: "2" },
                { label: "3 zones", value: "3" },
                { label: "4 zones", value: "4" },
              ],
              orderRole: "mode",
              performanceReason: "Splits the canvas into two to four brand regions.",
              performanceRole: "responsiveness",
              target: "yard.zoneCount",
              type: "select",
            },
            zone1Slot: {
              defaultValue: 1,
              description: "Palette slot for zone 1 or the top-left quadrant.",
              label: "Zone 1",
              max: 8,
              min: 1,
              orderRole: "color",
              performanceReason: "Maps zone 1 to a palette color.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.zone1Slot",
              type: "slider",
            },
            zone2Slot: {
              defaultValue: 2,
              description: "Palette slot for zone 2 or the top-right quadrant.",
              label: "Zone 2",
              max: 8,
              min: 1,
              orderRole: "color",
              performanceReason: "Maps zone 2 to a palette color.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.zone2Slot",
              type: "slider",
            },
            zone3Slot: {
              defaultValue: 3,
              description: "Palette slot for zone 3 or the bottom-left quadrant.",
              label: "Zone 3",
              max: 8,
              min: 1,
              orderRole: "color",
              performanceReason: "Maps zone 3 to a palette color.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.zone3Slot",
              type: "slider",
            },
            zone4Slot: {
              defaultValue: 4,
              description: "Palette slot for zone 4 or the bottom-right quadrant.",
              label: "Zone 4",
              max: 8,
              min: 1,
              orderRole: "color",
              performanceReason: "Maps zone 4 to a palette color.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.zone4Slot",
              type: "slider",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["zone1Slot", "zone2Slot"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["zone3Slot", "zone4Slot"],
              layout: "inline",
            },
          ],
          title: "Brand Zones",
          visibleWhen: { oneOf: ["zones", "quadrants"], target: "yard.colorMode" },
        },
        {
          controls: {
            stripeOrientation: {
              defaultValue: "diagonal",
              description: "Direction of highlight bands across the yard.",
              label: "Stripe axis",
              options: [
                { label: "Horizontal", value: "horizontal" },
                { label: "Vertical", value: "vertical" },
                { label: "Diagonal", value: "diagonal" },
              ],
              orderRole: "mode",
              performanceReason: "Rotates stripe band direction.",
              performanceRole: "responsiveness",
              target: "yard.stripeOrientation",
              type: "select",
            },
            stripeRepeat: {
              defaultValue: 6,
              description: "Number of stripe bands across the canvas.",
              label: "Stripe count",
              max: 16,
              min: 2,
              orderRole: "strength",
              performanceReason: "Increases stripe density.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.stripeRepeat",
              type: "slider",
            },
            stripeWidth: {
              defaultValue: 40,
              description: "Highlight band width as a percentage of each stripe period.",
              label: "Stripe width",
              max: 90,
              min: 10,
              orderRole: "strength",
              performanceReason: "Widens or narrows highlight bands.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.stripeWidth",
              type: "slider",
              unit: "%",
            },
            stripeColorSlot: {
              defaultValue: 1,
              description: "Palette slot used for highlight stripe containers.",
              label: "Highlight",
              max: 8,
              min: 1,
              orderRole: "detail",
              performanceReason: "Chooses which palette color forms the stripes.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.stripeColorSlot",
              type: "slider",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["stripeRepeat", "stripeWidth"],
              layout: "inline",
            },
          ],
          title: "Highlight Stripes",
          visibleWhen: { equals: "stripes", target: "yard.colorMode" },
        },
        {
          controls: {
            seed: {
              defaultValue: 42,
              description:
                "Deterministic seed for color layout. In ASCII Palette mode, changing seed reshuffles which palette color maps to each image region.",
              label: "Seed",
              max: 9999,
              min: 0,
              orderRole: "detail",
              performanceReason: "Drives palette and gap pseudo-random picks.",
              performanceRole: "responsiveness",
              step: 1,
              target: "yard.seed",
              type: "slider",
            },
            shuffle: {
              actions: [{ label: "Shuffle", value: "shuffle-colors" }],
              defaultValue: null,
              label: false,
              orderRole: "action",
              performanceReason: "Advances the seed to reshuffle palette assignment and procedural gaps.",
              performanceRole: "responsiveness",
              target: "yard.shuffle",
              type: "actions",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["seed", "shuffle"],
              layout: "inline",
            },
          ],
          title: "Randomize",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: false,
              label: "Include",
              performanceReason: "Toggles whether the product background paints behind containers.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: { hex: "#0A0A0A" },
              label: false,
              performanceReason: "Product background color.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "background"],
              layout: "inline",
            },
          ],
          title: "Background",
        },
        {
          controls: {
            exportKind: {
              defaultValue: "image",
              description: "Choose still image or timeline video output for the Export button.",
              label: "Output",
              options: [
                { label: "Image", value: "image" },
                { label: "Video", value: "video" },
              ],
              orderRole: "mode",
              performanceReason: "Switches sticky export between still and video pipelines.",
              performanceRole: "responsiveness",
              target: "export.kind",
              type: "select",
            },
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
                { label: "SVG", value: "svg" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses export encoding.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
              visibleWhen: { equals: "image", target: "export.kind" },
            },
            videoFormat: {
              defaultValue: "mp4",
              label: "Format",
              options: [
                { label: "MP4", value: "mp4" },
                { label: "WebM", value: "webm" },
                { label: "MOV", value: "mov" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses alpha video container: MP4 baseline, WebM alpha, or ProRes MOV.",
              performanceRole: "responsiveness",
              target: "export.video.format",
              type: "select",
              visibleWhen: { equals: "video", target: "export.kind" },
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Preset",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              performanceReason: "Sets export long-edge pixels.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
              visibleWhen: { equals: "image", target: "export.kind" },
            },
            videoResolution: {
              defaultValue: "current",
              label: "Preset",
              options: [
                { label: "Current", value: "current" },
                { label: "4K", value: "4k" },
              ],
              orderRole: "detail",
              performanceReason: "Sets video export pixel dimensions.",
              performanceRole: "workload",
              target: "export.video.resolution",
              type: "select",
              visibleWhen: { equals: "video", target: "export.kind" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["imageFormat", "imageResolution"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["videoFormat", "videoResolution"],
              layout: "inline",
            },
          ],
          title: "Export Settings",
        },
        {
          controls: {
            exportActions: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export",
                  value: "export",
                  variant: "default",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
            },
          },
          title: "Export",
        },
      ],
    },
  },
});
