import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const largeCanvasWorkloadFixture = {
  kind: "large-canvas" as const,
  loadProfile: {
    hardLimit: { height: 2160, width: 3840 },
    metric: "canvas-area" as const,
    smoothTarget: { height: 2160, width: 3840 },
    smoothTargetRatio: 1,
    target: "canvas.size",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "A 3840x2160 canvas is the heavy app baseline: the field fills the whole product canvas before the measured control is stressed.",
  value: { height: 2160, width: 3840 },
};

const densityStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "streams.density",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum stream density traces the most streamlines per frame.",
  value: 100,
};

const packedSpacingWorkloadFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { gap: 0, spacingMode: "packed" },
    metric: "custom" as const,
    smoothTarget: { gap: 0, spacingMode: "packed" },
    smoothTargetRatio: 1,
    target: "streams.spacingMode",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Packed spacing with width-aware collision is the heavy spacing baseline.",
  value: { gap: 0, spacingMode: "packed" },
};

const sizeVarietyStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "stroke.sizeVariety",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum size variety samples XL stroke classes across the field.",
  value: 100,
};

const smoothnessStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "streams.smoothness",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum smoothness uses the finest RK4 integration steps.",
  value: 100,
};

const lengthMinStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 320,
    metric: "numeric-max" as const,
    smoothTarget: 320,
    smoothTargetRatio: 1,
    target: "streams.lengthMin",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum length min stretches short stream segments across the field.",
  value: 320,
};

const lengthContrastStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "streams.lengthContrast",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Full length contrast varies streamline lengths across the field.",
  value: 100,
};


const pathReachStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 150,
    metric: "numeric-max" as const,
    smoothTarget: 150,
    smoothTargetRatio: 1,
    target: "paths.reach",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum reach extends path attractor influence across the canvas.",
  value: 150,
};

const pathStrengthStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "paths.strength",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum strength fully bends the vector field along paths.",
  value: 100,
};

const flowDirectionStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 360,
    metric: "numeric-max" as const,
    smoothTarget: 360,
    smoothTargetRatio: 1,
    target: "flow.direction",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum direction rotation retraces the full field.",
  value: 360,
};

const flowFrequencyStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "flow.frequency",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum scale packs the most procedural detail into the field.",
  value: 100,
};

const flowSwirlStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "flow.swirl",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum swirl adds the strongest rotational bias.",
  value: 100,
};

const flowTurbulenceStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "flow.turbulence",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum turbulence adds the strongest curl-noise distortion.",
  value: 100,
};

const flowSeedStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 9999,
    metric: "numeric-max" as const,
    smoothTarget: 9999,
    smoothTargetRatio: 1,
    target: "flow.seed",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum seed explores the upper procedural variation range.",
  value: 9999,
};

const streamsLengthMaxStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 480,
    metric: "numeric-max" as const,
    smoothTarget: 480,
    smoothTargetRatio: 1,
    target: "streams.lengthMax",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum length max traces the longest streamlines.",
  value: 480,
};

const strokeHeadSizeStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 3,
    metric: "numeric-max" as const,
    smoothTarget: 3,
    smoothTargetRatio: 1,
    target: "stroke.headSize",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum head scale draws the largest arrowheads.",
  value: 3,
};

const strokeWidthBySpeedStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "stroke.widthBySpeed",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum width-by-speed modulates ribbon width across every point.",
  value: 100,
};

const flowPatternStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { pattern: "turbulent" },
    metric: "custom" as const,
    smoothTarget: { pattern: "turbulent" },
    smoothTargetRatio: 1,
    target: "flow.pattern",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Turbulent pattern is the heaviest procedural field equation.",
  value: { pattern: "turbulent" },
};

const flowRandomizeSeedStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "randomize-seed" },
    metric: "custom" as const,
    smoothTarget: { action: "randomize-seed" },
    smoothTargetRatio: 1,
    target: "flow.randomizeSeed",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Randomize advances the seed and retraces streamlines.",
  value: { action: "randomize-seed" },
};

const flowSnapAnglesStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { snapAngles: "90" },
    metric: "custom" as const,
    smoothTarget: { snapAngles: "90" },
    smoothTargetRatio: 1,
    target: "flow.snapAngles",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "90° snap quantizes every sampled field angle.",
  value: { snapAngles: "90" },
};

const flowShuffleStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "shuffle" },
    metric: "custom" as const,
    smoothTarget: { action: "shuffle" },
    smoothTargetRatio: 1,
    target: "flow.shuffle",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Shuffle retraces streamlines after randomizing art parameters.",
  value: { action: "shuffle" },
};

const streamsSpacingModeStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { spacingMode: "packed" },
    metric: "custom" as const,
    smoothTarget: { spacingMode: "packed" },
    smoothTargetRatio: 1,
    target: "streams.spacingMode",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Packed spacing retraces with width-aware collision.",
  value: { spacingMode: "packed" },
};

const streamsGapStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 24,
    metric: "numeric-max" as const,
    smoothTarget: 24,
    smoothTargetRatio: 1,
    target: "streams.gap",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum gap widens packed stroke separation.",
  value: 24,
};

const streamsMarginStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 120,
    metric: "numeric-max" as const,
    smoothTarget: 120,
    smoothTargetRatio: 1,
    target: "streams.margin",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum margin insets streamline seeds from canvas edges.",
  value: 120,
};

const pathsAddStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "add-path" },
    metric: "custom" as const,
    smoothTarget: { action: "add-path" },
    smoothTargetRatio: 1,
    target: "paths.addPath",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Adding a path retraces streamlines with a new attractor.",
  value: { action: "add-path" },
};

const pathsDeleteStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "delete-path" },
    metric: "custom" as const,
    smoothTarget: { action: "delete-path" },
    smoothTargetRatio: 1,
    target: "paths.deletePath",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Deleting a path retraces streamlines without the attractor.",
  value: { action: "delete-path" },
};

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["field-trace", "stroke-draw"],
        targets: [
          "flow.pattern",
          "flow.texturePreset",
          "flow.randomizeSeed",
          "paths.editMode",
          "paths.addPath",
          "paths.deletePath",
          "stroke.style",
          "stroke.taper",
          "stroke.sizeVariety",
          "color.palette",
          "color.assignmentMode",
          "color.custom1",
          "flow.shuffle",
          "flow.snapAngles",
          "streams.spacingMode",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["field-trace", "stroke-draw"],
        targets: [
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "flow.seed",
          "paths.reach",
          "paths.strength",
          "streams.density",
          "streams.lengthMin",
          "streams.lengthMax",
          "streams.lengthContrast",
          "streams.smoothness",
          "stroke.width",
          "stroke.widthBySpeed",
          "stroke.headSize",
          "stroke.sizeVariety",
          "streams.gap",
          "streams.margin",
          "streams.spacingMode",
          "color.palette",
          "color.custom1",
          "color.opacity",
        ],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["field-trace", "stroke-draw"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["field-trace", "stroke-draw"],
        targets: ["canvas.offset"],
      },
      {
        interaction: "export",
        invalidates: ["stroke-draw"],
        targets: ["export.image.resolution", "export.image.format"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "flow.seed",
          "paths.reach",
          "paths.strength",
          "streams.density",
          "streams.lengthMin",
          "streams.lengthMax",
          "streams.lengthContrast",
          "streams.smoothness",
          "stroke.style",
          "stroke.width",
          "canvas.size",
          "paths.data",
        ],
        id: "field-trace",
        inputs: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "flow.seed",
          "paths.reach",
          "paths.strength",
          "streams.density",
          "streams.lengthMin",
          "streams.lengthMax",
          "streams.lengthContrast",
          "streams.smoothness",
          "stroke.style",
          "stroke.width",
          "canvas.size",
          "paths.data",
        ],
        invalidatedBy: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "flow.seed",
          "paths.reach",
          "paths.strength",
          "streams.density",
          "streams.lengthMin",
          "streams.lengthMax",
          "streams.lengthContrast",
          "streams.smoothness",
          "stroke.style",
          "stroke.width",
          "canvas.size",
          "paths.data",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "field-trace",
          "stroke.taper",
          "stroke.widthBySpeed",
          "stroke.headSize",
          "stroke.sizeVariety",
          "color.palette",
          "color.assignmentMode",
          "color.opacity",
          "color.custom1",
          "appearance.background",
          "canvas.size",
          "canvas.renderScale",
        ],
        id: "stroke-draw",
        inputs: [
          "field-trace",
          "stroke.taper",
          "stroke.widthBySpeed",
          "stroke.headSize",
          "stroke.sizeVariety",
          "color.palette",
          "color.assignmentMode",
          "color.opacity",
          "color.custom1",
          "appearance.background",
          "export.includeBackground",
        ],
        invalidatedBy: [
          "field-trace",
          "stroke.taper",
          "stroke.widthBySpeed",
          "stroke.headSize",
          "stroke.sizeVariety",
          "color.palette",
          "color.assignmentMode",
          "color.opacity",
          "color.custom1",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Thin marker strokes can alias without device-pixel-ratio x render-scale backing; mitigated by canvas.renderScale and a scaled backing store.",
    ],
    layers: [
      {
        content: ["geometry"],
        exportMode: "included",
        id: "flow-strokes",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-flow-canvas]",
      },
    ],
    performanceRisks: [
      "Glyph count scales with streams.density squared and with canvas area; mitigated by caching the field-trace pass and a density hard limit, and measured by the preview-render and export-copy scenarios.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "vector",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "vector-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM/SVG nodes for thousands of vector-output glyphs cause layout and GC pressure and slow export rasterization.",
      "WebGL/WebGPU is unnecessary for static vector-output fills and complicates pixel-accurate PNG export/copy; canvas-2d exportRenderer gives product-quality export parity with the preview.",
    ],
  },
  rendererWorkload: "vector-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: preview render stays under budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000, maxRenderMs: 2000 },
      expectedObservable:
        "The flow field renders the full grid of markers within the preview budget at max density.",
      fixture: "max density field",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport stays stable",
      browser: true,
      browserTestName: "browser perf: viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable:
        "Panning the canvas keeps frame gaps small because the field is not re-rasterized.",
      fixture: "default field",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport zoom stays stable under load",
      browser: true,
      browserTestName: "browser perf: viewport zoom stays stable under load",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      expectedObservable:
        "Zooming a dense field stays smooth because zoom is a CSS transform, not a re-render.",
      fixture: "max density field",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export png stays under budget",
      browser: true,
      browserTestName: "browser perf: export png stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Exporting an 8K PNG of a dense field completes within the export budget.",
      fixture: "8k export of dense field",
      id: "export-copy",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: pattern change stays responsive",
      browser: true,
      browserTestName: "browser perf: pattern change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Pattern",
      expectedObservable: "Switching the flow pattern updates the field within budget.",
      fixture: "default field",
      id: "flow-pattern-change",
      interaction: "control-change",
      target: "flow.pattern",
      values: { default: "currents", max: "turbulent", min: "currents" },
      workload: true,
      stressFixture: flowPatternStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: direction drag stays responsive",
      browser: true,
      browserTestName: "browser perf: direction drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Direction",
      expectedObservable: "Dragging direction rotates the field with live feedback.",
      fixture: "default field",
      id: "flow-direction-drag",
      interaction: "control-drag",
      target: "flow.direction",
      values: { default: 200, max: 360, min: 0 },
      workload: true,
      stressFixture: flowDirectionStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: scale drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Scale",
      expectedObservable: "Dragging scale rescales features with live feedback.",
      fixture: "default field",
      id: "flow-scale-drag",
      interaction: "control-drag",
      target: "flow.frequency",
      values: { default: 14, max: 100, min: 0 },
      workload: true,
      stressFixture: flowFrequencyStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: swirl drag stays responsive",
      browser: true,
      browserTestName: "browser perf: swirl drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Swirl",
      expectedObservable: "Dragging swirl bends the field with live feedback.",
      fixture: "default field",
      id: "flow-swirl-drag",
      interaction: "control-drag",
      target: "flow.swirl",
      values: { default: 8, max: 100, min: -100 },
      workload: true,
      stressFixture: flowSwirlStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: turbulence drag stays responsive",
      browser: true,
      browserTestName: "browser perf: turbulence drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Turbulence",
      expectedObservable: "Dragging turbulence distorts the field with live feedback.",
      fixture: "default field",
      id: "flow-turbulence-drag",
      interaction: "control-drag",
      target: "flow.turbulence",
      values: { default: 10, max: 100, min: 0 },
      workload: true,
      stressFixture: flowTurbulenceStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: density drag stays responsive",
      browser: true,
      browserTestName: "browser perf: density drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Density",
      expectedObservable:
        "Dragging density to the maximum keeps live feedback while drawing the most markers.",
      fixture: "max density on large canvas",
      id: "streams-density-drag",
      interaction: "control-drag",
      stressFixture: densityStressFixture,
      target: "streams.density",
      values: { default: 22, max: 60, min: 6 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: smoothness drag stays responsive",
      browser: true,
      browserTestName: "browser perf: smoothness drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Smoothness",
      expectedObservable: "Dragging smoothness refines RK4 integration with live feedback.",
      fixture: "max smoothness on large canvas",
      id: "streams-smoothness-drag",
      interaction: "control-drag",
      target: "streams.smoothness",
      values: { default: 72, max: 100, min: 0 },
      workload: true,
      stressFixture: smoothnessStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: marker style change stays responsive",
      browser: true,
      browserTestName: "browser perf: marker style change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Style",
      expectedObservable: "Switching marker style re-rasterizes the field within budget.",
      fixture: "default field",
      id: "stroke-style-change",
      interaction: "control-change",
      target: "stroke.style",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: marker length drag stays responsive",
      browser: true,
      browserTestName: "browser perf: marker length drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Length",
      expectedObservable: "Dragging marker length resizes glyphs with live feedback.",
      fixture: "default field",
      id: "streams-length-max-drag",
      interaction: "control-drag",
      target: "streams.lengthMax",
      values: { default: 220, max: 480, min: 8 },
      workload: true,
      stressFixture: streamsLengthMaxStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: marker thickness drag stays responsive",
      browser: true,
      browserTestName: "browser perf: marker thickness drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Thickness",
      expectedObservable: "Dragging marker thickness re-strokes glyphs with live feedback.",
      fixture: "default field",
      id: "stroke-width-drag",
      interaction: "control-drag",
      target: "stroke.width",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: palette change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Palette",
      expectedObservable: "Switching palette repaints streamlines within budget.",
      fixture: "default field",
      id: "color-palette-change",
      interaction: "control-change",
      target: "color.palette",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: color assignment change stays responsive",
      browser: true,
      browserTestName: "browser perf: color assignment change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Assignment",
      expectedObservable: "Switching assignment mode repaints streamlines within budget.",
      fixture: "default field",
      id: "color-assignment-change",
      interaction: "control-change",
      target: "color.assignmentMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: packed xl size variety stays responsive",
      browser: true,
      browserTestName: "browser perf: packed xl size variety stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Size variety",
      expectedObservable: "Packed spacing with XL size variety stays responsive on a large canvas.",
      fixture: "packed spacing max density on large canvas",
      id: "packed-xl-size-variety",
      interaction: "control-drag",
      target: "stroke.sizeVariety",
      values: { default: 15, max: 100, min: 0 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
      stressFixture: sizeVarietyStressFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: snap angles change stays responsive",
      browser: true,
      browserTestName: "browser perf: snap angles change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Snap angles",
      expectedObservable: "Switching snap angles retraces the field within budget.",
      fixture: "default field",
      id: "flow-snap-angles-change",
      interaction: "control-change",
      target: "flow.snapAngles",
      values: { default: "off", max: "90", min: "off" },
      workload: true,
      stressFixture: flowSnapAnglesStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: shuffle stays responsive",
      browser: true,
      browserTestName: "browser perf: shuffle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Shuffle",
      expectedObservable: "Clicking Shuffle stays responsive.",
      fixture: "default field",
      id: "flow-shuffle-change",
      interaction: "control-change",
      target: "flow.shuffle",
      values: { default: "shuffle", max: "shuffle", min: "shuffle" },
      workload: true,
      stressFixture: flowShuffleStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: spacing mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: spacing mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Spacing mode",
      expectedObservable: "Switching spacing mode retraces streamlines within budget.",
      fixture: "default field",
      id: "streams-spacing-mode-change",
      interaction: "control-change",
      target: "streams.spacingMode",
      values: { default: "even", max: "packed", min: "loose" },
      workload: true,
      stressFixture: streamsSpacingModeStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: gap drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Gap",
      expectedObservable: "Dragging Gap in packed mode stays responsive.",
      fixture: "packed spacing on large canvas",
      id: "streams-gap-drag",
      interaction: "control-drag",
      target: "streams.gap",
      values: { default: 4, max: 24, min: 0 },
      workload: true,
      stressFixture: streamsGapStressFixture,
      workloadFixture: packedSpacingWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: margin drag stays responsive",
      browser: true,
      browserTestName: "browser perf: margin drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Margin",
      expectedObservable: "Dragging Margin insets streamline seeds within budget.",
      fixture: "default field",
      id: "streams-margin-drag",
      interaction: "control-drag",
      target: "streams.margin",
      values: { default: 24, max: 120, min: 0 },
      workload: true,
      stressFixture: streamsMarginStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: stream opacity drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stream opacity drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Stream opacity",
      expectedObservable: "Dragging Stream opacity repaints strokes within budget.",
      fixture: "default field",
      id: "color-opacity-drag",
      interaction: "control-drag",
      target: "color.opacity",
      values: { default: 100, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: custom palette color change stays responsive",
      browser: true,
      browserTestName: "browser perf: custom palette color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color 1",
      expectedObservable: "Changing a custom palette slot re-rasterizes the field within budget.",
      fixture: "custom palette field",
      id: "color-custom-change",
      interaction: "control-change",
      target: "color.custom1",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: custom palette slot 2 change stays responsive",
      browser: true,
      browserTestName: "browser perf: custom palette slot 2 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color 2",
      expectedObservable: "Changing custom palette slot 2 re-rasterizes within budget.",
      fixture: "custom palette field",
      id: "color-custom2-change",
      interaction: "control-change",
      target: "color.custom2",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: custom palette slot 3 change stays responsive",
      browser: true,
      browserTestName: "browser perf: custom palette slot 3 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color 3",
      expectedObservable: "Changing custom palette slot 3 re-rasterizes within budget.",
      fixture: "custom palette field",
      id: "color-custom3-change",
      interaction: "control-change",
      target: "color.custom3",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: custom palette slot 4 change stays responsive",
      browser: true,
      browserTestName: "browser perf: custom palette slot 4 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color 4",
      expectedObservable: "Changing custom palette slot 4 re-rasterizes within budget.",
      fixture: "custom palette field",
      id: "color-custom4-change",
      interaction: "control-change",
      target: "color.custom4",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: custom palette slot 5 change stays responsive",
      browser: true,
      browserTestName: "browser perf: custom palette slot 5 change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color 5",
      expectedObservable: "Changing custom palette slot 5 re-rasterizes within budget.",
      fixture: "custom palette field",
      id: "color-custom5-change",
      interaction: "control-change",
      target: "color.custom5",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: include background change stays responsive",
      browser: true,
      browserTestName: "browser perf: include background change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable: "Toggling Include shows or hides the product background within budget.",
      fixture: "default field",
      id: "include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Background",
      expectedObservable: "Changing the background color repaints the fill within budget.",
      fixture: "default field",
      id: "background-color-change",
      interaction: "control-change",
      target: "appearance.background",
      uiSelector: "[data-toolcraft-flow-canvas]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image format change stays responsive",
      browser: true,
      browserTestName: "browser perf: image format change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Switching export format stays responsive and affects export only.",
      fixture: "default field",
      id: "image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image resolution change stays responsive",
      browser: true,
      browserTestName: "browser perf: image resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Selecting 8K export resolution stays responsive; it scales export size, not the preview.",
      fixture: "8k resolution on large canvas",
      id: "image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "custom",
        reason: "8K is the heaviest export resolution and the largest rasterization target.",
        value: { resolution: "8k" },
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: paths strength drag stays responsive",
      browser: true,
      browserTestName: "browser perf: paths strength drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Strength",
      expectedObservable: "Dragging Strength with a path present updates field bending within budget.",
      fixture: "path on large canvas",
      id: "paths-strength-drag",
      interaction: "control-drag",
      target: "paths.strength",
      values: { default: 55, max: 100, min: 0 },
      workload: true,
      stressFixture: pathStrengthStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: paths reach drag stays responsive",
      browser: true,
      browserTestName: "browser perf: paths reach drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Reach",
      expectedObservable: "Dragging Reach with a path present updates falloff within budget.",
      fixture: "path on large canvas",
      id: "paths-reach-drag",
      interaction: "control-drag",
      target: "paths.reach",
      values: { default: 45, max: 150, min: 0 },
      workload: true,
      stressFixture: pathReachStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: paths edit mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: paths edit mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Edit paths",
      expectedObservable: "Toggling Edit paths shows or hides the overlay within budget.",
      fixture: "default field",
      id: "paths-edit-mode-change",
      interaction: "control-change",
      target: "paths.editMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: add path stays responsive",
      browser: true,
      browserTestName: "browser perf: add path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Paths",
      expectedObservable: "Clicking Add path stays responsive.",
      fixture: "default field",
      id: "paths-add-path-change",
      interaction: "control-change",
      target: "paths.addPath",
      values: { default: "add-path", max: "add-path", min: "add-path" },
      workload: true,
      stressFixture: pathsAddStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: delete path stays responsive",
      browser: true,
      browserTestName: "browser perf: delete path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Delete path",
      expectedObservable: "Clicking Delete path stays responsive.",
      fixture: "guide path present",
      id: "paths-delete-path-change",
      interaction: "control-change",
      target: "paths.deletePath",
      values: { default: "delete-path", max: "delete-path", min: "delete-path" },
      workload: true,
      stressFixture: pathsDeleteStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: streams length contrast drag stays responsive",
      browser: true,
      browserTestName: "browser perf: streams length contrast drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Length contrast",
      expectedObservable: "Dragging Length contrast varies streamline lengths within budget.",
      fixture: "max density on large canvas",
      id: "streams-length-contrast-drag",
      interaction: "control-drag",
      stressFixture: lengthContrastStressFixture,
      target: "streams.lengthContrast",
      values: { default: 75, max: 100, min: 0 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },

    {
      automated: true,
      automatedTestName: "perf: stroke taper change stays responsive",
      browser: true,
      browserTestName: "browser perf: stroke taper change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Taper",
      expectedObservable: "Switching taper mode re-renders streamlines within budget.",
      fixture: "default field",
      id: "stroke-taper-change",
      interaction: "control-change",
      target: "stroke.taper",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stroke head size drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stroke head size drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Arrow head",
      expectedObservable: "When Style is Arrow, dragging Arrow head stays responsive.",
      fixture: "default field arrow style",
      id: "stroke-head-size-drag",
      interaction: "control-drag",
      target: "stroke.headSize",
      values: { default: 1, max: 3, min: 0.25 },
      workload: true,
      stressFixture: strokeHeadSizeStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: field preset change stays responsive",
      browser: true,
      browserTestName: "browser perf: field preset change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Preset",
      expectedObservable: "Switching field preset stays responsive.",
      fixture: "default field",
      id: "flow-texture-preset-change",
      interaction: "control-change",
      target: "flow.texturePreset",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: seed drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Seed",
      expectedObservable: "Dragging seed explores procedural field variations within budget.",
      fixture: "default field",
      id: "flow-seed-drag",
      interaction: "control-drag",
      target: "flow.seed",
      values: { default: 21, max: 9999, min: 0 },
      workload: true,
      stressFixture: flowSeedStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: randomize seed stays responsive",
      browser: true,
      browserTestName: "browser perf: randomize seed stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Randomize",
      expectedObservable: "Clicking Randomize stays responsive.",
      fixture: "default field",
      id: "flow-randomize-seed-change",
      interaction: "control-change",
      target: "flow.randomizeSeed",
      values: { default: "randomize-seed", max: "randomize-seed", min: "randomize-seed" },
      workload: true,
      stressFixture: flowRandomizeSeedStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: streams length min drag stays responsive",
      browser: true,
      browserTestName: "browser perf: streams length min drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Length min",
      expectedObservable: "Dragging Length min stays responsive.",
      fixture: "default field",
      id: "streams-length-min-drag",
      interaction: "control-drag",
      target: "streams.lengthMin",
      values: { default: 10, max: 320, min: 4 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
      stressFixture: lengthMinStressFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: stroke width by speed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: stroke width by speed drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Width by speed",
      expectedObservable: "Dragging Width by speed stays responsive.",
      fixture: "default field",
      id: "stroke-width-by-speed-drag",
      interaction: "control-drag",
      target: "stroke.widthBySpeed",
      values: { default: 35, max: 100, min: 0 },
      workload: true,
      stressFixture: strokeWidthBySpeedStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: export svg stays under budget",
      browser: true,
      browserTestName: "browser perf: export svg stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Exporting an SVG of a dense field completes within the export budget.",
      fixture: "svg export of dense field",
      id: "export-svg",
      interaction: "export-copy",
      stressFixture: densityStressFixture,
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "streams.density",
    "streams.smoothness",
    "streams.lengthContrast",
    "streams.lengthMin",
    "streams.lengthMax",
    "flow.pattern",
    "flow.direction",
    "flow.frequency",
    "flow.swirl",
    "flow.turbulence",
    "flow.seed",
    "flow.randomizeSeed",
    "flow.shuffle",
    "flow.snapAngles",
    "paths.reach",
    "paths.strength",
    "paths.addPath",
    "paths.deletePath",
    "stroke.widthBySpeed",
    "stroke.headSize",
    "stroke.sizeVariety",
    "streams.spacingMode",
    "streams.gap",
    "streams.margin",
    "export.image.resolution",
  ],
});
