import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const largeCanvasWorkloadFixture = {
  kind: "large-canvas" as const,
  loadProfile: {
    hardLimit: { height: 2160, width: 3840 },
    metric: "canvas-area" as const,
    smoothTarget: { height: 2160, width: 3840 },
    smoothTargetRatio: 1,
    target: "canvas.size",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "A 3840x2160 canvas is the heavy app baseline: the field fills the whole product canvas before the measured control is stressed.",
  value: { height: 2160, width: 3840 },
};

const densityStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 60,
    metric: "numeric-max" as const,
    smoothTarget: 60,
    smoothTargetRatio: 1,
    target: "field.density",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum grid density produces the most glyph draws per frame.",
  value: 60,
};

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["field-sample", "glyph-draw"],
        targets: [
          "flow.pattern",
          "marker.style",
          "marker.color",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
          "guides.editMode",
          "guides.maskUninfluenced",
          "guides.addPath",
          "guides.deletePath",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["field-sample", "glyph-draw"],
        targets: [
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "field.density",
          "field.jitter",
          "marker.length",
          "marker.thickness",
          "guides.influence",
          "guides.reach",
          "guides.addPath",
          "guides.deletePath",
        ],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["field-sample", "glyph-draw"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["field-sample", "glyph-draw"],
        targets: ["canvas.offset"],
      },
      {
        interaction: "export",
        invalidates: ["glyph-draw"],
        targets: ["export.image.resolution", "export.image.format"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "field.density",
          "field.jitter",
          "guides.influence",
          "guides.reach",
          "guides.maskUninfluenced",
          "canvas.size",
        ],
        id: "field-sample",
        inputs: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "field.density",
          "field.jitter",
          "guides.influence",
          "guides.reach",
          "guides.maskUninfluenced",
          "canvas.size",
        ],
        invalidatedBy: [
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "field.density",
          "field.jitter",
          "guides.influence",
          "guides.reach",
          "guides.maskUninfluenced",
          "canvas.size",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "field-sample",
          "marker.style",
          "marker.length",
          "marker.thickness",
          "marker.color",
          "appearance.background",
          "canvas.size",
          "canvas.renderScale",
        ],
        id: "glyph-draw",
        inputs: [
          "field-sample",
          "marker.style",
          "marker.length",
          "marker.thickness",
          "marker.color",
          "appearance.background",
          "export.includeBackground",
        ],
        invalidatedBy: [
          "field-sample",
          "marker.style",
          "marker.length",
          "marker.thickness",
          "marker.color",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Thin marker strokes can alias without device-pixel-ratio x render-scale backing; mitigated by canvas.renderScale and a scaled backing store.",
    ],
    layers: [
      {
        content: ["geometry"],
        exportMode: "included",
        id: "flow-markers",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-flow-canvas]",
      },
    ],
    performanceRisks: [
      "Glyph count scales with field.density squared and with canvas area; mitigated by caching the field-sample pass and a density hard limit, and measured by the preview-render and export-copy scenarios.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "vector",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "vector-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM/SVG nodes for thousands of vector-output glyphs cause layout and GC pressure and slow export rasterization.",
      "WebGL/WebGPU is unnecessary for static vector-output fills and complicates pixel-accurate PNG export/copy; canvas-2d exportRenderer gives product-quality export parity with the preview.",
    ],
  },
  rendererWorkload: "vector-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: preview render stays under budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000, maxRenderMs: 2000 },
      expectedObservable:
        "The flow field renders the full grid of markers within the preview budget at max density.",
      fixture: "max density field",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport stays stable",
      browser: true,
      browserTestName: "browser perf: viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable:
        "Panning the canvas keeps frame gaps small because the field is not re-rasterized.",
      fixture: "default field",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport zoom stays stable under load",
      browser: true,
      browserTestName: "browser perf: viewport zoom stays stable under load",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      expectedObservable:
        "Zooming a dense field stays smooth because zoom is a CSS transform, not a re-render.",
      fixture: "max density field",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export png stays under budget",
      browser: true,
      browserTestName: "browser perf: export png stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Exporting an 8K PNG of a dense field completes within the export budget.",
      fixture: "8k export of dense field",
      id: "export-copy",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: pattern change stays responsive",
      browser: true,
      browserTestName: "browser perf: pattern change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Pattern",
      expectedObservable: "Switching the flow pattern updates the field within budget.",
      fixture: "default field",
      id: "flow-pattern-change",
      interaction: "control-change",
      target: "flow.pattern",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: direction drag stays responsive",
      browser: true,
      browserTestName: "browser perf: direction drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Direction",
      expectedObservable: "Dragging direction rotates the field with live feedback.",
      fixture: "default field",
      id: "flow-direction-drag",
      interaction: "control-drag",
      target: "flow.direction",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: frequency drag stays responsive",
      browser: true,
      browserTestName: "browser perf: frequency drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Frequency",
      expectedObservable: "Dragging frequency rescales features with live feedback.",
      fixture: "default field",
      id: "flow-frequency-drag",
      interaction: "control-drag",
      target: "flow.frequency",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: swirl drag stays responsive",
      browser: true,
      browserTestName: "browser perf: swirl drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Swirl",
      expectedObservable: "Dragging swirl bends the field with live feedback.",
      fixture: "default field",
      id: "flow-swirl-drag",
      interaction: "control-drag",
      target: "flow.swirl",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: turbulence drag stays responsive",
      browser: true,
      browserTestName: "browser perf: turbulence drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Turbulence",
      expectedObservable: "Dragging turbulence distorts the field with live feedback.",
      fixture: "default field",
      id: "flow-turbulence-drag",
      interaction: "control-drag",
      target: "flow.turbulence",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: density drag stays responsive",
      browser: true,
      browserTestName: "browser perf: density drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Density",
      expectedObservable:
        "Dragging density to the maximum keeps live feedback while drawing the most markers.",
      fixture: "max density on large canvas",
      id: "field-density-drag",
      interaction: "control-drag",
      stressFixture: densityStressFixture,
      target: "field.density",
      values: { default: 22, max: 60, min: 6 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: jitter drag stays responsive",
      browser: true,
      browserTestName: "browser perf: jitter drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Jitter",
      expectedObservable: "Dragging jitter offsets markers with live feedback.",
      fixture: "default field",
      id: "field-jitter-drag",
      interaction: "control-drag",
      target: "field.jitter",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: marker style change stays responsive",
      browser: true,
      browserTestName: "browser perf: marker style change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Style",
      expectedObservable: "Switching marker style re-rasterizes the field within budget.",
      fixture: "default field",
      id: "marker-style-change",
      interaction: "control-change",
      target: "marker.style",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: marker length drag stays responsive",
      browser: true,
      browserTestName: "browser perf: marker length drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Length",
      expectedObservable: "Dragging marker length resizes glyphs with live feedback.",
      fixture: "default field",
      id: "marker-length-drag",
      interaction: "control-drag",
      target: "marker.length",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: marker thickness drag stays responsive",
      browser: true,
      browserTestName: "browser perf: marker thickness drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Thickness",
      expectedObservable: "Dragging marker thickness re-strokes glyphs with live feedback.",
      fixture: "default field",
      id: "marker-thickness-drag",
      interaction: "control-drag",
      target: "marker.thickness",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: marker color change stays responsive",
      browser: true,
      browserTestName: "browser perf: marker color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color",
      expectedObservable: "Changing marker color re-rasterizes the field within budget.",
      fixture: "default field",
      id: "marker-color-change",
      interaction: "control-change",
      target: "marker.color",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: include background change stays responsive",
      browser: true,
      browserTestName: "browser perf: include background change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable: "Toggling Include shows or hides the product background within budget.",
      fixture: "default field",
      id: "include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Background",
      expectedObservable: "Changing the background color repaints the fill within budget.",
      fixture: "default field",
      id: "background-color-change",
      interaction: "control-change",
      target: "appearance.background",
      uiSelector: "[data-toolcraft-flow-canvas]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image format change stays responsive",
      browser: true,
      browserTestName: "browser perf: image format change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Switching export format stays responsive and affects export only.",
      fixture: "default field",
      id: "image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image resolution change stays responsive",
      browser: true,
      browserTestName: "browser perf: image resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Selecting 8K export resolution stays responsive; it scales export size, not the preview.",
      fixture: "8k resolution on large canvas",
      id: "image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "custom",
        reason: "8K is the heaviest export resolution and the largest rasterization target.",
        value: { resolution: "8k" },
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: guides influence drag stays responsive",
      browser: true,
      browserTestName: "browser perf: guides influence drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Influence",
      expectedObservable: "Dragging Influence with guides present updates the field within budget.",
      fixture: "guide path on large canvas",
      id: "guides-influence-drag",
      interaction: "control-drag",
      target: "guides.influence",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: guides reach drag stays responsive",
      browser: true,
      browserTestName: "browser perf: guides reach drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Reach",
      expectedObservable: "Dragging Reach with guides present updates falloff within budget.",
      fixture: "guide path on large canvas",
      id: "guides-reach-drag",
      interaction: "control-drag",
      target: "guides.reach",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: guides linear mask toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: guides linear mask toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Linear only",
      expectedObservable: "Toggling Linear only culls distant markers within budget.",
      fixture: "guide path on large canvas",
      id: "guides-mask-toggle",
      interaction: "control-change",
      target: "guides.maskUninfluenced",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: guides edit mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: guides edit mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Edit guides",
      expectedObservable: "Toggling Edit guides shows or hides the overlay within budget.",
      fixture: "default field",
      id: "guides-edit-mode-change",
      interaction: "control-change",
      target: "guides.editMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: add guide path stays responsive",
      browser: true,
      browserTestName: "browser perf: add guide path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Paths",
      expectedObservable: "Clicking Add path stays responsive.",
      fixture: "default field",
      id: "guides-add-path-change",
      interaction: "control-change",
      target: "guides.addPath",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: delete guide path stays responsive",
      browser: true,
      browserTestName: "browser perf: delete guide path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Delete path",
      expectedObservable: "Clicking Delete path stays responsive.",
      fixture: "guide path present",
      id: "guides-delete-path-change",
      interaction: "control-change",
      target: "guides.deletePath",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export svg stays under budget",
      browser: true,
      browserTestName: "browser perf: export svg stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Exporting an SVG of a dense field completes within the export budget.",
      fixture: "svg export of dense field",
      id: "export-svg",
      interaction: "export-copy",
      stressFixture: densityStressFixture,
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: ["field.density", "export.image.resolution"],
});
