import { defineToolcraft } from "@/toolcraft/runtime";

/**
 * Flow Field 3.0 — art-grade pattern engine with probabilistic palettes,
 * width-aware spacing, size variety, and shuffle workflow. Canvas 2D custom renderer.
 */
export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  export: {
    png: {
      background: "include",
    },
  },
  persistence: { storage: "none" },
  settingsTransfer: { appId: "flow-field" },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            editMode: {
              defaultValue: false,
              description: "Draw and drag flow paths directly on the canvas.",
              label: "Edit paths",
              orderRole: "mode",
              performanceReason: "Enables the path overlay for direct manipulation.",
              performanceRole: "responsiveness",
              target: "paths.editMode",
              type: "switch",
            },
            reach: {
              defaultValue: 45,
              description: "How far path influence extends from each spline.",
              label: "Reach",
              max: 150,
              min: 0,
              orderRole: "strength",
              performanceReason: "Scales path attractor falloff and retraces streamlines.",
              performanceRole: "workload",
              step: 1,
              target: "paths.reach",
              type: "slider",
              unit: "%",
            },
            strength: {
              defaultValue: 55,
              description: "How strongly paths bend the vector field (0 = decoration only).",
              label: "Strength",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Blends path tangents into the field; retraces streamlines.",
              performanceRole: "workload",
              step: 1,
              target: "paths.strength",
              type: "slider",
              unit: "%",
            },
            addPath: {
              actions: [{ label: "Add path", value: "add-path" }],
              defaultValue: null,
              label: "Paths",
              orderRole: "action",
              performanceReason: "Creates a new empty path for canvas editing.",
              performanceRole: "workload",
              target: "paths.addPath",
              type: "actions",
            },
            deletePath: {
              actions: [{ label: "Delete path", value: "delete-path" }],
              defaultValue: null,
              label: false,
              orderRole: "action",
              performanceReason: "Removes the active path and retraces streamlines.",
              performanceRole: "workload",
              target: "paths.deletePath",
              type: "actions",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["reach", "strength"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["addPath", "deletePath"],
              layout: "inline",
            },
          ],
          title: "Flow Paths",
        },
        {
          controls: {
            texturePreset: {
              defaultValue: "calm",
              label: "Preset",
              options: [
                { label: "Off", value: "off" },
                { label: "Calm drift", value: "calm" },
                { label: "Soft ripple", value: "ripple" },
                { label: "Storm", value: "storm" },
              ],
              orderRole: "mode",
              performanceReason: "Retunes field frequency, swirl, turbulence, and stream density.",
              performanceRole: "responsiveness",
              target: "flow.texturePreset",
              type: "select",
            },
            pattern: {
              defaultValue: "currents",
              label: "Pattern",
              options: [
                { label: "Currents", value: "currents" },
                { label: "Vortex", value: "vortex" },
                { label: "Waves", value: "waves" },
                { label: "Turbulent", value: "turbulent" },
                { label: "Radial", value: "radial" },
              ],
              orderRole: "mode",
              performanceReason: "Switches the procedural field equation and retraces streamlines.",
              performanceRole: "workload",
              target: "flow.pattern",
              type: "select",
            },
            direction: {
              defaultValue: 200,
              label: "Direction",
              max: 360,
              min: 0,
              orderRole: "primary",
              performanceReason: "Rotates the base flow field.",
              performanceRole: "workload",
              step: 1,
              target: "flow.direction",
              type: "slider",
              unit: "°",
            },
            frequency: {
              defaultValue: 14,
              label: "Scale",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Scales procedural feature size in the vector field.",
              performanceRole: "workload",
              step: 1,
              target: "flow.frequency",
              type: "slider",
            },
            swirl: {
              defaultValue: 8,
              label: "Swirl",
              max: 100,
              min: -100,
              orderRole: "strength",
              performanceReason: "Adds rotational bias to the vector field.",
              performanceRole: "workload",
              step: 1,
              target: "flow.swirl",
              type: "slider",
            },
            turbulence: {
              defaultValue: 10,
              label: "Turbulence",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Adds curl-noise distortion to the vector field.",
              performanceRole: "workload",
              step: 1,
              target: "flow.turbulence",
              type: "slider",
            },
            snapAngles: {
              defaultValue: "off",
              description: "Quantizes field angles for sharp architectural compositions.",
              label: "Snap angles",
              options: [
                { label: "Off", value: "off" },
                { label: "45°", value: "45" },
                { label: "60°", value: "60" },
                { label: "90°", value: "90" },
              ],
              orderRole: "detail",
              performanceReason: "Snaps sampled field angles to fixed increments.",
              performanceRole: "workload",
              target: "flow.snapAngles",
              type: "select",
            },
            seed: {
              defaultValue: 21,
              description: "Deterministic seed for procedural field variation.",
              label: "Seed",
              max: 9999,
              min: 0,
              orderRole: "detail",
              performanceReason: "Changes procedural noise without retracing layout seeds.",
              performanceRole: "workload",
              step: 1,
              target: "flow.seed",
              type: "slider",
            },
            randomizeSeed: {
              actions: [{ label: "Randomize", value: "randomize-seed" }],
              defaultValue: null,
              label: false,
              orderRole: "action",
              performanceReason: "Advances the field seed to explore new variations.",
              performanceRole: "workload",
              target: "flow.randomizeSeed",
              type: "actions",
            },
            shuffle: {
              actions: [{ label: "Shuffle", value: "shuffle" }],
              defaultValue: null,
              description: "Randomize seed, palette, pattern, variety, and spacing within curated ranges.",
              label: false,
              orderRole: "action",
              performanceReason: "One-click tasteful randomization of art parameters.",
              performanceRole: "workload",
              target: "flow.shuffle",
              type: "actions",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["texturePreset", "pattern"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["frequency", "direction"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["swirl", "turbulence"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["snapAngles", "seed"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["randomizeSeed", "shuffle"],
              layout: "inline",
            },
          ],
          title: "Field",
        },
        {
          controls: {
            spacingMode: {
              defaultValue: "even",
              description: "Packed mode uses stroke width for collision spacing.",
              label: "Spacing mode",
              options: [
                { label: "Even", value: "even" },
                { label: "Packed", value: "packed" },
                { label: "Loose", value: "loose" },
              ],
              orderRole: "mode",
              performanceReason: "Changes collision spacing between streamlines.",
              performanceRole: "workload",
              target: "streams.spacingMode",
              type: "select",
            },
            density: {
              defaultValue: 16,
              description: "Stream separation — higher values pack more streamlines.",
              label: "Density",
              max: 100,
              min: 1,
              orderRole: "primary",
              performanceReason: "Dominant workload: more streamlines traced per frame.",
              performanceRole: "workload",
              step: 1,
              target: "streams.density",
              type: "slider",
            },
            lengthMin: {
              defaultValue: 10,
              label: "Length min",
              max: 320,
              min: 4,
              orderRole: "primary",
              performanceReason: "Minimum streamline length in slow/tight regions.",
              performanceRole: "workload",
              step: 1,
              target: "streams.lengthMin",
              type: "slider",
              unit: "px",
            },
            lengthMax: {
              defaultValue: 220,
              label: "Length max",
              max: 480,
              min: 8,
              orderRole: "primary",
              performanceReason: "Maximum streamline length in fast/straight regions.",
              performanceRole: "workload",
              step: 1,
              target: "streams.lengthMax",
              type: "slider",
              unit: "px",
            },
            lengthContrast: {
              defaultValue: 75,
              description: "Mix between short ticks and long currents along the field.",
              label: "Length contrast",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Varies traced streamline lengths by local speed and curvature.",
              performanceRole: "workload",
              step: 1,
              target: "streams.lengthContrast",
              type: "slider",
              unit: "%",
            },
            smoothness: {
              defaultValue: 72,
              description: "RK4 integration step fineness and path subdivision density.",
              label: "Smoothness",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Finer integration steps increase trace point count.",
              performanceRole: "workload",
              step: 1,
              target: "streams.smoothness",
              type: "slider",
            },
            gap: {
              defaultValue: 4,
              description: "Breathing room between packed strokes.",
              label: "Gap",
              max: 24,
              min: 0,
              orderRole: "detail",
              performanceReason: "Adds gap between width-aware packed strokes.",
              performanceRole: "workload",
              step: 0.5,
              target: "streams.gap",
              type: "slider",
              unit: "px",
              visibleWhen: { equals: "packed", target: "streams.spacingMode" },
            },
            margin: {
              defaultValue: 24,
              description: "Composition inset keeping strokes off canvas edges.",
              label: "Margin",
              max: 120,
              min: 0,
              orderRole: "detail",
              performanceReason: "Insets streamline seeds from canvas edges.",
              performanceRole: "workload",
              step: 1,
              target: "streams.margin",
              type: "slider",
              unit: "px",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["spacingMode", "density"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["lengthMin", "lengthMax"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["lengthContrast", "smoothness"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["gap", "margin"],
              layout: "inline",
            },
          ],
          title: "Streams",
        },
        {
          controls: {
            style: {
              defaultValue: "line",
              label: "Style",
              options: [
                { label: "Line", value: "line" },
                { label: "Arrow", value: "arrow" },
                { label: "Dash", value: "dash" },
                { label: "Rectangle", value: "rectangle" },
                { label: "Hatch", value: "hatch" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses centerline, arrowhead, or dashed stream rendering.",
              performanceRole: "responsiveness",
              target: "stroke.style",
              type: "select",
            },
            width: {
              defaultValue: 2,
              label: "Width",
              max: 12,
              min: 0.5,
              orderRole: "primary",
              performanceReason: "Base stroke width before taper and speed scaling.",
              performanceRole: "responsiveness",
              step: 0.5,
              target: "stroke.width",
              type: "slider",
              unit: "px",
            },
            widthBySpeed: {
              defaultValue: 35,
              description: "Thicken streamlines in faster regions of the field.",
              label: "Width by speed",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Thicken streamlines in faster regions by field speed.",
              performanceRole: "responsiveness",
              step: 1,
              target: "stroke.widthBySpeed",
              type: "slider",
              unit: "%",
            },
            sizeVariety: {
              defaultValue: 15,
              description: "Per-stroke width classes: thin, base, thick, and XL.",
              label: "Size variety",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Samples per-stroke width classes for art-grade variety.",
              performanceRole: "workload",
              step: 1,
              target: "stroke.sizeVariety",
              type: "slider",
              unit: "%",
            },
            taper: {
              defaultValue: "tail",
              label: "Taper",
              options: [
                { label: "None", value: "none" },
                { label: "Tail", value: "tail" },
                { label: "Head", value: "head" },
                { label: "Both", value: "both" },
              ],
              orderRole: "detail",
              performanceReason: "Variable-width ribbon geometry along each streamline.",
              performanceRole: "responsiveness",
              target: "stroke.taper",
              type: "select",
            },
            headSize: {
              defaultValue: 1,
              description: "Arrowhead extent relative to stroke width.",
              label: "Arrow head",
              max: 3,
              min: 0.25,
              orderRole: "detail",
              performanceReason: "Arrowhead extent at streamline tips relative to stroke width.",
              performanceRole: "workload",
              step: 0.05,
              target: "stroke.headSize",
              type: "slider",
              visibleWhen: { oneOf: ["arrow"], target: "stroke.style" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["style", "width"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["widthBySpeed", "sizeVariety"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["taper", "headSize"],
              layout: "inline",
            },
          ],
          title: "Stroke",
        },
        {
          controls: {
            palette: {
              defaultValue: "ocean",
              description: "Curated stream color palette.",
              label: "Palette",
              options: [
                { label: "Ocean", value: "ocean" },
                { label: "Ember", value: "ember" },
                { label: "Newsprint", value: "newsprint" },
                { label: "Golden hour", value: "golden-hour" },
                { label: "Neon", value: "neon" },
                { label: "Monochrome", value: "monochrome" },
                { label: "Ink", value: "ink" },
                { label: "Pastel", value: "pastel" },
                { label: "Twilight", value: "twilight" },
                { label: "Custom", value: "custom" },
              ],
              orderRole: "mode",
              performanceReason: "Curated probabilistic color palette for strokes.",
              performanceRole: "responsiveness",
              target: "color.palette",
              type: "select",
            },
            assignmentMode: {
              defaultValue: "weighted",
              description: "How palette colors are assigned to strokes.",
              label: "Assignment",
              options: [
                { label: "Weighted random", value: "weighted" },
                { label: "Neighbor inheritance", value: "inheritance" },
                { label: "By speed", value: "speed" },
                { label: "Vertical gradient", value: "vertical" },
              ],
              orderRole: "detail",
              performanceReason: "How palette colors are assigned to strokes.",
              performanceRole: "responsiveness",
              target: "color.assignmentMode",
              type: "select",
            },
            opacity: {
              defaultValue: 100,
              label: "Stream opacity",
              max: 100,
              min: 0,
              orderRole: "detail",
              performanceReason: "Stroke color opacity.",
              performanceRole: "responsiveness",
              step: 1,
              target: "color.opacity",
              type: "slider",
              unit: "%",
            },
            custom1: {
              defaultValue: { hex: "#1B3A6B" },
              description: "Palette color slot 1 when Palette is Custom.",
              label: false,
              orderRole: "detail",
              performanceReason: "Palette color slot 1 when Palette is Custom.",
              performanceRole: "responsiveness",
              target: "color.custom1",
              type: "color",
              visibleWhen: { equals: "custom", target: "color.palette" },
            },
            custom2: {
              defaultValue: { hex: "#4DA6FF" },
              description: "Palette color slot 2 when Palette is Custom.",
              label: false,
              orderRole: "detail",
              performanceReason: "Palette color slot 2 when Palette is Custom.",
              performanceRole: "responsiveness",
              target: "color.custom2",
              type: "color",
              visibleWhen: { equals: "custom", target: "color.palette" },
            },
            custom3: {
              defaultValue: { hex: "#8FD4FF" },
              description: "Palette color slot 3 when Palette is Custom.",
              label: false,
              orderRole: "detail",
              performanceReason: "Palette color slot 3 when Palette is Custom.",
              performanceRole: "responsiveness",
              target: "color.custom3",
              type: "color",
              visibleWhen: { equals: "custom", target: "color.palette" },
            },
            custom4: {
              defaultValue: { hex: "#E8F4FF" },
              description: "Palette color slot 4 when Palette is Custom.",
              label: false,
              orderRole: "detail",
              performanceReason: "Palette color slot 4 when Palette is Custom.",
              performanceRole: "responsiveness",
              target: "color.custom4",
              type: "color",
              visibleWhen: { equals: "custom", target: "color.palette" },
            },
            custom5: {
              defaultValue: { hex: "#FFFFFF" },
              description: "Palette color slot 5 when Palette is Custom.",
              label: false,
              orderRole: "detail",
              performanceReason: "Palette color slot 5 when Palette is Custom.",
              performanceRole: "responsiveness",
              target: "color.custom5",
              type: "color",
              visibleWhen: { equals: "custom", target: "color.palette" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["palette", "assignmentMode"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["opacity"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["custom1", "custom2"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["custom3", "custom4"],
              layout: "inline",
            },
            {
              columns: 2,
              controls: ["custom5"],
              layout: "inline",
            },
          ],
          title: "Palette",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: true,
              label: "Include",
              performanceReason: "Toggles whether the product background paints behind streamlines.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: { hex: "#0A1E3D" },
              label: false,
              performanceReason: "Product background color.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "background"],
              layout: "inline",
            },
          ],
          title: "Background",
        },
        {
          controls: {
            imageFormat: {
              defaultValue: "svg",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
                { label: "SVG", value: "svg" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses export encoding.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              defaultValue: "2k",
              label: "Preset",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              performanceReason: "Sets export long-edge pixels.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["imageFormat", "imageResolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
        },
        {
          controls: {
            exportActionsSvg: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export SVG",
                  value: "export-png",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy SVG",
                  value: "copy-png",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "svg", target: "export.image.format" },
            },
            exportActionsPng: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  value: "export-png",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy PNG",
                  value: "copy-png",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "png", target: "export.image.format" },
            },
            exportActionsJpg: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export JPG",
                  value: "export-png",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy JPG",
                  value: "copy-png",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "jpg", target: "export.image.format" },
            },
          },
          title: "Export",
        },
      ],
      title: "Controls",
    },
  },
  toolbar: {
    history: true,
    radar: true,
    zoom: true,
  },
});
