import { defineToolcraft } from "@/toolcraft/runtime";

/**
 * Word Tide — typographic texture generator for brand system #2. Readable
 * words fill the canvas as a dither grid or along traced flow streamlines;
 * an optional source image drives ink density and tone zones, and an optional
 * shape mask constrains placement. Canvas 2D preview, PNG/JPG/SVG export.
 */
export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  export: {
    png: {
      background: "include",
    },
  },
  persistence: { storage: "none" },
  settingsTransfer: { appId: "word-tide" },
  panels: {
    controls: {
      title: "Controls",
      sections: [
        {
          controls: {
            renderMode: {
              defaultValue: "flow",
              description:
                "Flow lays words along traced currents; Dither fills a text grid driven by the source image.",
              label: "Mode",
              options: [
                { label: "Flow", value: "flow" },
                { label: "Dither", value: "dither" },
              ],
              orderRole: "mode",
              performanceReason: "Switches between streamline and grid word layout engines.",
              performanceRole: "responsiveness",
              target: "mode.render",
              type: "segmented",
            },
            seed: {
              defaultValue: 21,
              label: "Seed",
              max: 9999,
              min: 0,
              orderRole: "detail",
              performanceReason: "Drives word order, jitter, dropout, and streamline seeding.",
              performanceRole: "responsiveness",
              step: 1,
              target: "tide.seed",
              type: "slider",
            },
            randomize: {
              actions: [{ label: "Randomize", value: "randomize-seed" }],
              defaultValue: null,
              label: false,
              orderRole: "action",
              performanceReason: "Advances the seed to reshuffle the whole texture.",
              performanceRole: "responsiveness",
              target: "tide.randomize",
              type: "actions",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["seed", "randomize"],
              layout: "inline",
            },
          ],
          title: "Texture Mode",
        },
        {
          controls: {
            list: {
              defaultValue:
                "OCEAN TIDE CURRENT HARBOR DOCK CARGO SWELL DRIFT NORTH ANCHOR VESSEL PORT",
              description:
                "Words or data tokens separated by spaces, commas, or new lines. Every token is placed whole and readable.",
              label: "Word list",
              orderRole: "input",
              performanceReason: "Token stream size changes measurement and placement workload.",
              performanceRole: "workload",
              target: "words.list",
              type: "code",
            },
            order: {
              defaultValue: "sequential",
              description: "Sequential repeats the list in order; Random draws a seeded shuffle.",
              label: "Word order",
              options: [
                { label: "Sequential", value: "sequential" },
                { label: "Random", value: "random" },
              ],
              orderRole: "mode",
              performanceReason: "Changes token pick per slot; relays out all words.",
              performanceRole: "responsiveness",
              target: "words.order",
              type: "select",
            },
          },
          title: "Words",
        },
        {
          controls: {
            sourceImage: {
              accept: "image/*",
              assetKind: "image",
              defaultValue: null,
              label: false,
              orderRole: "input",
              performanceReason: "Uploads the image whose luminance drives per-word ink.",
              performanceRole: "responsiveness",
              target: "media.sourceImage",
              type: "fileDrop",
            },
          },
          title: "Source Image",
        },
        {
          controls: {
            invert: {
              defaultValue: false,
              description: "Read light-on-dark sources: light areas receive dense ink.",
              label: "Invert",
              orderRole: "mode",
              performanceReason: "Flips the luminance-to-ink reading for every word.",
              performanceRole: "responsiveness",
              target: "source.invert",
              type: "switch",
            },
            fade: {
              defaultValue: true,
              description:
                "Map ink to word opacity. Off keeps placed words at full strength for a binary dither look.",
              label: "Fade",
              orderRole: "mode",
              performanceReason: "Switches per-word alpha between ink ramp and constant.",
              performanceRole: "responsiveness",
              target: "ink.fade",
              type: "switch",
            },
            contrast: {
              defaultValue: 0,
              description:
                "Crushes or lifts source luminance like After Effects Levels — strong positive values push midtones toward black and white.",
              label: "Source levels",
              max: 100,
              min: -100,
              orderRole: "strength",
              performanceReason: "Re-inks every placed word from resampled luminance.",
              performanceRole: "responsiveness",
              step: 1,
              target: "source.contrast",
              type: "slider",
            },
            sparsity: {
              defaultValue: 0,
              description: "Drops words out of light areas first, thinning the texture.",
              label: "Sparsity",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Skips placed words, changing draw count.",
              performanceRole: "workload",
              step: 1,
              target: "ink.sparsity",
              type: "slider",
              unit: "%",
            },
          },
          title: "Ink Mapping",
        },
        {
          controls: {
            enabled: {
              defaultValue: false,
              description:
                "Fill dark, mid, and light tone bands from separate word lists. Without a source image, bands follow canvas height.",
              label: "Zones",
              orderRole: "mode",
              performanceReason: "Adds per-slot band lookup and separate token streams.",
              performanceRole: "responsiveness",
              target: "zones.enabled",
              type: "switch",
            },
            darkWords: {
              defaultValue: "OCEAN DEEP UNDERTOW",
              description: "Words for the darkest band. Empty falls back to the main word list.",
              label: "Dark words",
              orderRole: "primary",
              performanceReason: "Separate token stream for dark slots.",
              performanceRole: "responsiveness",
              target: "zones.dark",
              type: "code",
              visibleWhen: { equals: true, target: "zones.enabled" },
            },
            midWords: {
              defaultValue: "BOAT HULL CARGO",
              description: "Words for the mid band. Empty falls back to the main word list.",
              label: "Mid words",
              orderRole: "primary",
              performanceReason: "Separate token stream for mid slots.",
              performanceRole: "responsiveness",
              target: "zones.mid",
              type: "code",
              visibleWhen: { equals: true, target: "zones.enabled" },
            },
            lightWords: {
              defaultValue: "CLOUDS SKY FOAM",
              description: "Words for the lightest band. Empty falls back to the main word list.",
              label: "Light words",
              orderRole: "primary",
              performanceReason: "Separate token stream for light slots.",
              performanceRole: "responsiveness",
              target: "zones.light",
              type: "code",
              visibleWhen: { equals: true, target: "zones.enabled" },
            },
            split: {
              defaultValue: [35, 65],
              description: "Luminance thresholds separating dark, mid, and light bands.",
              label: "Band split",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Moves band boundaries; reassigns word lists per slot.",
              performanceRole: "responsiveness",
              step: 1,
              target: "zones.split",
              type: "rangeSlider",
              unit: "%",
              visibleWhen: { equals: true, target: "zones.enabled" },
            },
          },
          title: "Tone Zones",
          visibleWhen: { equals: "dither", target: "mode.render" },
        },
        {
          controls: {
            gap: {
              defaultValue: 6,
              description: "Extra spacing between words and rows in pixels. At 0, words pack flush.",
              label: "Gap",
              max: 60,
              min: 0,
              orderRole: "primary",
              performanceReason: "Lower gap packs more words per canvas; minimum is the stress case.",
              performanceRole: "workload",
              step: 1,
              target: "grid.gap",
              type: "slider",
              unit: "px",
            },
            overlap: {
              defaultValue: false,
              description:
                "When on, words in very dark ink areas pack over each other for a denser dither.",
              label: "Overlap",
              orderRole: "mode",
              performanceReason: "Tightens horizontal advance in high-ink slots; relays out words.",
              performanceRole: "workload",
              target: "grid.overlap",
              type: "switch",
            },
            spacingBias: {
              defaultValue: 0,
              description:
                "Center keeps uniform gap. Left tightens darker zones; right tightens lighter zones.",
              label: "Tone spacing",
              max: 100,
              min: -100,
              orderRole: "primary",
              performanceReason: "Scales per-slot gaps from sampled luminance; relays out words.",
              performanceRole: "workload",
              step: 1,
              target: "grid.spacingBias",
              type: "slider",
            },
            spacingRange: {
              defaultValue: 50,
              description: "How strongly tone spacing tightens or loosens gaps.",
              label: "Spacing range",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Amplifies luminance-driven gap multipliers.",
              performanceRole: "workload",
              step: 1,
              target: "grid.spacingRange",
              type: "slider",
              unit: "%",
            },
            jitter: {
              defaultValue: 0,
              description: "Random positional offset breaking the strict grid.",
              label: "Jitter",
              max: 100,
              min: 0,
              orderRole: "detail",
              performanceReason: "Adds per-slot offsets; relays out all words.",
              performanceRole: "workload",
              step: 1,
              target: "grid.jitter",
              type: "slider",
              unit: "%",
            },
          },
          title: "Word Grid",
          visibleWhen: { equals: "dither", target: "mode.render" },
        },
        {
          controls: {
            pattern: {
              defaultValue: "currents",
              label: "Pattern",
              options: [
                { label: "Currents", value: "currents" },
                { label: "Waves", value: "waves" },
                { label: "Vortex", value: "vortex" },
                { label: "Radial", value: "radial" },
                { label: "Turbulent", value: "turbulent" },
              ],
              orderRole: "mode",
              performanceReason: "Switches the procedural vector field; retraces streamlines.",
              performanceRole: "responsiveness",
              target: "flow.pattern",
              type: "select",
            },
            direction: {
              defaultValue: 200,
              label: "Direction",
              max: 360,
              min: 0,
              orderRole: "spatial",
              performanceReason: "Rotates the base field; retraces streamlines.",
              performanceRole: "responsiveness",
              step: 1,
              target: "flow.direction",
              type: "slider",
              unit: "°",
            },
            frequency: {
              defaultValue: 14,
              description: "How tightly the field pattern repeats across the canvas.",
              label: "Scale",
              max: 40,
              min: 2,
              orderRole: "strength",
              performanceReason: "Changes field curvature; retraces streamlines.",
              performanceRole: "workload",
              step: 1,
              target: "flow.frequency",
              type: "slider",
            },
            swirl: {
              defaultValue: 8,
              label: "Swirl",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Bends field angles; retraces streamlines.",
              performanceRole: "responsiveness",
              step: 1,
              target: "flow.swirl",
              type: "slider",
              unit: "%",
            },
            turbulence: {
              defaultValue: 10,
              label: "Turbulence",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Adds noise to field angles; retraces streamlines.",
              performanceRole: "responsiveness",
              step: 1,
              target: "flow.turbulence",
              type: "slider",
              unit: "%",
            },
          },
          title: "Flow Field",
          visibleWhen: { equals: "flow", target: "mode.render" },
        },
        {
          controls: {
            editMode: {
              defaultValue: false,
              description: "Draw and drag guide paths directly on the canvas to steer the current.",
              label: "Edit paths",
              orderRole: "mode",
              performanceReason: "Enables the path overlay for direct manipulation.",
              performanceRole: "responsiveness",
              target: "paths.editMode",
              type: "switch",
            },
            reach: {
              defaultValue: 45,
              description: "How far path influence extends from each spline.",
              label: "Reach",
              max: 150,
              min: 0,
              orderRole: "strength",
              performanceReason: "Scales path attractor falloff; retraces streamlines.",
              performanceRole: "workload",
              step: 1,
              target: "paths.reach",
              type: "slider",
              unit: "%",
            },
            strength: {
              defaultValue: 55,
              description: "How strongly paths bend the current (0 = no influence).",
              label: "Strength",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Blends path tangents into the field; retraces streamlines.",
              performanceRole: "workload",
              step: 1,
              target: "paths.strength",
              type: "slider",
              unit: "%",
            },
            addPath: {
              actions: [{ label: "Add path", value: "add-path" }],
              defaultValue: null,
              label: "Paths",
              orderRole: "action",
              performanceReason: "Creates a new empty guide path for canvas editing.",
              performanceRole: "workload",
              target: "paths.addPath",
              type: "actions",
            },
            deletePath: {
              actions: [{ label: "Delete path", value: "delete-path" }],
              defaultValue: null,
              label: false,
              orderRole: "action",
              performanceReason: "Removes the active guide path; retraces streamlines.",
              performanceRole: "workload",
              target: "paths.deletePath",
              type: "actions",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["addPath", "deletePath"],
              layout: "inline",
            },
          ],
          title: "Flow Paths",
          visibleWhen: { equals: "flow", target: "mode.render" },
        },
        {
          controls: {
            density: {
              defaultValue: 55,
              description: "How tightly word streams pack together.",
              label: "Density",
              max: 100,
              min: 0,
              orderRole: "primary",
              performanceReason: "Maximum density traces the most streamlines and words.",
              performanceRole: "workload",
              step: 1,
              target: "streams.density",
              type: "slider",
              unit: "%",
            },
            wordGap: {
              defaultValue: 6,
              description: "Extra spacing between consecutive words on a stream.",
              label: "Word gap",
              max: 80,
              min: 0,
              orderRole: "detail",
              performanceReason: "Lower gap places more words per streamline.",
              performanceRole: "workload",
              step: 1,
              target: "streams.wordGap",
              type: "slider",
              unit: "px",
            },
          },
          title: "Flow Words",
          visibleWhen: { equals: "flow", target: "mode.render" },
        },
        {
          controls: {
            fontSize: {
              defaultValue: 18,
              description: "Word size in pixels. Tay Big Bird always renders uppercase.",
              label: "Font size",
              max: 120,
              min: 8,
              orderRole: "primary",
              performanceReason: "Font size sets word slot counts and measurement workload.",
              performanceRole: "workload",
              step: 1,
              target: "type.fontSize",
              type: "slider",
              unit: "px",
            },
          },
          title: "Typography",
        },
        {
          controls: {
            count: {
              defaultValue: 1,
              description: "How many brand colors map across ink density from dark to light.",
              label: "Color count",
              max: 4,
              min: 1,
              orderRole: "mode",
              performanceReason: "Adds per-word color buckets in preview and export.",
              performanceRole: "workload",
              step: 1,
              target: "colors.count",
              type: "slider",
              variant: "discrete",
            },
            color1: {
              defaultValue: { hex: "#053239" },
              label: "Deep Teal",
              orderRole: "color",
              performanceReason: "Darkest ink color slot.",
              performanceRole: "responsiveness",
              target: "colors.color1",
              type: "color",
            },
            color2: {
              defaultValue: { hex: "#354852" },
              label: "Dark Slate",
              orderRole: "color",
              performanceReason: "Second ink color slot.",
              performanceRole: "responsiveness",
              target: "colors.color2",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 2, target: "colors.count" },
            },
            color3: {
              defaultValue: { hex: "#00C1EF" },
              label: "Capri",
              orderRole: "color",
              performanceReason: "Third ink color slot.",
              performanceRole: "responsiveness",
              target: "colors.color3",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 3, target: "colors.count" },
            },
            color4: {
              defaultValue: { hex: "#8BE5FF" },
              label: "Sky Blue",
              orderRole: "color",
              performanceReason: "Lightest ink color slot.",
              performanceRole: "responsiveness",
              target: "colors.color4",
              type: "color",
              visibleWhen: { greaterThanOrEqual: 4, target: "colors.count" },
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["color1", "color2", "color3", "color4"],
              layout: "inline",
            },
          ],
          title: "Brand Palette",
        },
        {
          controls: {
            words: {
              defaultValue: "",
              description: "Words that always receive a marker highlight, matched case-insensitively.",
              label: "Words",
              orderRole: "input",
              performanceReason: "Adds highlight rects behind matched words.",
              performanceRole: "responsiveness",
              target: "highlight.words",
              type: "text",
            },
            color: {
              defaultValue: { hex: "#8BE5FF" },
              label: false,
              orderRole: "color",
              performanceReason: "Marker rect fill color.",
              performanceRole: "responsiveness",
              target: "highlight.color",
              type: "color",
            },
            coverage: {
              defaultValue: 0,
              description: "Share of words highlighted at random in addition to matched words.",
              label: "Coverage",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Adds highlight rect draws per covered word.",
              performanceRole: "workload",
              step: 1,
              target: "highlight.coverage",
              type: "slider",
              unit: "%",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["words", "color"],
              layout: "inline",
            },
          ],
          title: "Highlights",
        },
        {
          controls: {
            maskImage: {
              accept: "image/svg+xml,image/png,image/webp",
              assetKind: "image",
              defaultValue: null,
              description:
                "SVG or PNG with transparency. Words are placed only where the whole word fits inside the shape.",
              label: false,
              orderRole: "input",
              performanceReason: "Rasterizes a shape alpha map that filters every placement.",
              performanceRole: "responsiveness",
              target: "media.maskImage",
              type: "fileDrop",
            },
            invert: {
              defaultValue: false,
              description: "Place words outside the shape instead of inside.",
              label: "Invert",
              orderRole: "mode",
              performanceReason: "Flips the mask alpha; relays out all words.",
              performanceRole: "responsiveness",
              target: "mask.invert",
              type: "switch",
            },
            feather: {
              defaultValue: 0,
              description: "Softens the mask edge so border words fade out.",
              label: "Feather",
              max: 60,
              min: 0,
              orderRole: "detail",
              performanceReason: "Blurs the mask alpha map on rebuild.",
              performanceRole: "workload",
              step: 1,
              target: "mask.feather",
              type: "slider",
              unit: "px",
            },
          },
          title: "Shape Mask",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: true,
              label: "Include",
              performanceReason: "Toggles whether the paper background paints behind words.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: { hex: "#F8F1E8" },
              label: false,
              performanceReason: "Product background color.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "background"],
              layout: "inline",
            },
          ],
          title: "Background",
        },
        {
          controls: {
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "SVG", value: "svg" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "mode",
              performanceReason: "Chooses export encoding.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            svgText: {
              defaultValue: "editable",
              description:
                "Editable keeps selectable text elements; Outlines converts words to print-ready vector paths when the brand font file is available.",
              label: "SVG text",
              options: [
                { label: "Editable text", value: "editable" },
                { label: "Outlined paths", value: "outlines" },
              ],
              orderRole: "mode",
              performanceReason: "Outline conversion shapes every word into path geometry.",
              performanceRole: "workload",
              target: "export.svg.text",
              type: "select",
              visibleWhen: { equals: "svg", target: "export.image.format" },
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Preset",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              performanceReason: "Sets export long-edge pixels.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["imageFormat", "imageResolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
        },
        {
          controls: {
            exportActionsSvg: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export SVG",
                  value: "export-image",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy SVG",
                  value: "copy-image",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "svg", target: "export.image.format" },
            },
            exportActionsPng: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  value: "export-image",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy PNG",
                  value: "copy-image",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "png", target: "export.image.format" },
            },
            exportActionsJpg: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export JPG",
                  value: "export-image",
                  variant: "default",
                },
                {
                  icon: "copy",
                  label: "Copy JPG",
                  value: "copy-image",
                  variant: "secondary",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
              visibleWhen: { equals: "jpg", target: "export.image.format" },
            },
          },
          title: "Export",
        },
      ],
    },
  },
});
