import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const largeCanvasWorkloadFixture = {
  kind: "large-canvas" as const,
  loadProfile: {
    hardLimit: { height: 2160, width: 3840 },
    metric: "canvas-area" as const,
    smoothTarget: { height: 2160, width: 3840 },
    smoothTargetRatio: 1,
    target: "canvas.size",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "A 3840x2160 canvas is the heavy app baseline: word slots scale with canvas area before the measured control is stressed.",
  value: { height: 2160, width: 3840 },
};

const sourceMediaWorkloadFixture = {
  kind: "media" as const,
  loadProfile: {
    hardLimit: { height: 1080, width: 1920 },
    metric: "media-area" as const,
    smoothTarget: { height: 1080, width: 1920 },
    smoothTargetRatio: 1,
    target: "media.sourceImage",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "A 1920x1080 source photo is the media baseline for per-word luminance sampling.",
  value: { height: 1080, width: 1920 },
};

const maskMediaWorkloadFixture = {
  kind: "media" as const,
  loadProfile: {
    hardLimit: { height: 1080, width: 1920 },
    metric: "media-area" as const,
    smoothTarget: { height: 1080, width: 1920 },
    smoothTargetRatio: 1,
    target: "media.maskImage",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "A 1920x1080 alpha shape is the mask baseline: the alpha map spans the whole canvas before feather is stressed.",
  value: { height: 1080, width: 1920 },
};

const wordListStressText = Array.from(
  { length: 1100 },
  (_, index) =>
    `TOKEN${index % 40} CARGO${index % 23} TIDE${index % 31} HARBOR${index % 17} ANCHOR${index % 13} VESSEL${index % 11}`,
).join("\n");

const wordListStressFixture = {
  kind: "large-text" as const,
  loadProfile: {
    hardLimit: wordListStressText,
    metric: "text-length" as const,
    smoothTarget: wordListStressText,
    smoothTargetRatio: 1,
    target: "words.list",
    userFacingRange: "fully-guaranteed" as const,
  },
  minChars: 50_000,
  minLines: 1000,
  reason:
    "A 6600-token, 1100-line word list is the heavy token-stream case for measurement caching and placement.",
  value: wordListStressText,
};

const densityStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "streams.density",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum density traces the most streamlines and places the most words.",
  value: 100,
};

const wordGapStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { wordGap: 0 },
    metric: "custom" as const,
    smoothTarget: { wordGap: 0 },
    smoothTargetRatio: 1,
    target: "streams.wordGap",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Zero word gap packs the most words onto every streamline.",
  value: { wordGap: 0 },
};

const gridGapStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { gap: 0 },
    metric: "custom" as const,
    smoothTarget: { gap: 0 },
    smoothTargetRatio: 1,
    target: "grid.gap",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Zero gap packs the densest word grid, maximizing slots and draws.",
  value: { gap: 0 },
};

const colorCountStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 4,
    metric: "numeric-max" as const,
    smoothTarget: 4,
    smoothTargetRatio: 1,
    target: "colors.count",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Four active palette slots maximize per-word color buckets in preview and export.",
  value: 4,
};

const sparsityStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { sparsity: 0 },
    metric: "custom" as const,
    smoothTarget: { sparsity: 0 },
    smoothTargetRatio: 1,
    target: "ink.sparsity",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Zero sparsity keeps every placed word, maximizing draw count.",
  value: { sparsity: 0 },
};

const gridJitterStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "grid.jitter",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum jitter relays out every slot with offsets.",
  value: 100,
};

const gridSpacingBiasStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "grid.spacingBias",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum tone spacing bias rescales gaps across luminance bands.",
  value: 100,
};

const gridSpacingRangeStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "grid.spacingRange",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum spacing range amplifies luminance-driven gap multipliers.",
  value: 100,
};

const smallFontStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 8,
    metric: "numeric-min" as const,
    smoothTarget: 8,
    smoothTargetRatio: 1,
    target: "type.fontSize",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "An 8px font size packs the most word slots per canvas area.",
  value: 8,
};

const flowFrequencyStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 40,
    metric: "numeric-max" as const,
    smoothTarget: 40,
    smoothTargetRatio: 1,
    target: "flow.frequency",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum scale packs the tightest field repetition and retraces the most streamlines.",
  value: 40,
};

const highlightCoverageStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "highlight.coverage",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Full coverage draws a marker rect behind every placed word.",
  value: 100,
};

const maskFeatherStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 60,
    metric: "numeric-max" as const,
    smoothTarget: 60,
    smoothTargetRatio: 1,
    target: "mask.feather",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum feather runs the widest separable blur over the mask alpha map.",
  value: 60,
};

const pathReachStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 150,
    metric: "numeric-max" as const,
    smoothTarget: 150,
    smoothTargetRatio: 1,
    target: "paths.reach",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum reach extends path attractor influence across the canvas.",
  value: 150,
};

const pathStrengthStressFixture = {
  kind: "max-value" as const,
  loadProfile: {
    hardLimit: 100,
    metric: "numeric-max" as const,
    smoothTarget: 100,
    smoothTargetRatio: 1,
    target: "paths.strength",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum strength fully bends the vector field along paths.",
  value: 100,
};

const pathsAddStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "add-path" },
    metric: "custom" as const,
    smoothTarget: { action: "add-path" },
    smoothTargetRatio: 1,
    target: "paths.addPath",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Adding a path retraces streamlines with a new attractor.",
  value: { action: "add-path" },
};

const pathsDeleteStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { action: "delete-path" },
    metric: "custom" as const,
    smoothTarget: { action: "delete-path" },
    smoothTargetRatio: 1,
    target: "paths.deletePath",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Deleting a path retraces streamlines without the attractor.",
  value: { action: "delete-path" },
};

const exportResolutionStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { resolution: "8k" },
    metric: "custom" as const,
    smoothTarget: { resolution: "8k" },
    smoothTargetRatio: 1,
    target: "export.image.resolution",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "8K is the heaviest export resolution and the largest rasterization target.",
  value: { resolution: "8k" },
};

const svgOutlinesStressFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: { svgText: "outlines" },
    metric: "custom" as const,
    smoothTarget: { svgText: "outlines" },
    smoothTargetRatio: 1,
    target: "export.svg.text",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Outline conversion shapes every placed word into vector path geometry.",
  value: { svgText: "outlines" },
};

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["word-layout", "word-draw"],
        targets: [
          "mode.render",
          "words.list",
          "words.order",
          "tide.randomize",
          "source.invert",
          "ink.fade",
          "zones.enabled",
          "zones.dark",
          "zones.mid",
          "zones.light",
          "flow.pattern",
          "paths.editMode",
          "paths.addPath",
          "paths.deletePath",
          "highlight.words",
          "mask.invert",
          "export.svg.text",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "media-import",
        invalidates: ["source-sample", "word-layout", "word-draw"],
        targets: ["media.sourceImage"],
      },
      {
        interaction: "media-import",
        invalidates: ["mask-raster", "word-layout", "word-draw"],
        targets: ["media.maskImage"],
      },
      {
        interaction: "control-drag",
        invalidates: ["word-layout", "word-draw"],
        targets: [
          "tide.seed",
          "source.contrast",
          "colors.count",
          "colors.color1",
          "colors.color2",
          "colors.color3",
          "colors.color4",
          "grid.spacingBias",
          "grid.spacingRange",
          "ink.sparsity",
          "zones.split",
          "grid.gap",
          "grid.overlap",
          "grid.jitter",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "paths.reach",
          "paths.strength",
          "streams.density",
          "streams.wordGap",
          "highlight.coverage",
          "type.fontSize",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["mask-raster", "word-layout", "word-draw"],
        targets: ["mask.feather"],
      },
      {
        interaction: "control-change",
        invalidates: ["word-draw"],
        targets: ["highlight.color", "appearance.background", "export.includeBackground"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["source-sample", "mask-raster", "word-layout"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["source-sample", "mask-raster", "word-layout"],
        targets: ["canvas.offset"],
      },
      {
        interaction: "export",
        invalidates: ["word-draw"],
        targets: ["export.image.resolution", "export.image.format", "export.svg.text"],
      },
    ],
    passes: [
      {
        cacheKey: ["media.sourceImage", "canvas.size"],
        id: "source-sample",
        inputs: ["media.sourceImage", "canvas.size"],
        invalidatedBy: ["media.sourceImage", "canvas.size"],
        kind: "rasterize",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["media.maskImage", "canvas.size", "mask.invert", "mask.feather"],
        id: "mask-raster",
        inputs: ["media.maskImage", "canvas.size", "mask.invert", "mask.feather"],
        invalidatedBy: ["media.maskImage", "canvas.size", "mask.invert", "mask.feather"],
        kind: "rasterize",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "mode.render",
          "tide.seed",
          "words.list",
          "words.order",
          "source.contrast",
          "source.invert",
          "ink.fade",
          "colors.count",
          "colors.color1",
          "colors.color2",
          "colors.color3",
          "colors.color4",
          "grid.spacingBias",
          "grid.spacingRange",
          "ink.sparsity",
          "zones.enabled",
          "zones.split",
          "zones.dark",
          "zones.mid",
          "zones.light",
          "grid.gap",
          "grid.overlap",
          "grid.jitter",
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "paths.reach",
          "paths.strength",
          "paths.data",
          "streams.density",
          "streams.wordGap",
          "highlight.words",
          "highlight.coverage",
          "type.fontSize",
          "canvas.size",
          "source-sample",
          "mask-raster",
        ],
        id: "word-layout",
        inputs: [
          "source-sample",
          "mask-raster",
          "mode.render",
          "tide.seed",
          "words.list",
          "words.order",
          "source.contrast",
          "source.invert",
          "ink.fade",
          "colors.count",
          "colors.color1",
          "colors.color2",
          "colors.color3",
          "colors.color4",
          "grid.spacingBias",
          "grid.spacingRange",
          "ink.sparsity",
          "zones.enabled",
          "zones.split",
          "zones.dark",
          "zones.mid",
          "zones.light",
          "grid.gap",
          "grid.overlap",
          "grid.jitter",
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "paths.reach",
          "paths.strength",
          "paths.data",
          "streams.density",
          "streams.wordGap",
          "highlight.words",
          "highlight.coverage",
          "type.fontSize",
          "canvas.size",
        ],
        invalidatedBy: [
          "source-sample",
          "mask-raster",
          "mode.render",
          "tide.seed",
          "words.list",
          "words.order",
          "source.contrast",
          "source.invert",
          "ink.fade",
          "colors.count",
          "colors.color1",
          "colors.color2",
          "colors.color3",
          "colors.color4",
          "grid.spacingBias",
          "grid.spacingRange",
          "ink.sparsity",
          "zones.enabled",
          "zones.split",
          "zones.dark",
          "zones.mid",
          "zones.light",
          "grid.gap",
          "grid.overlap",
          "grid.jitter",
          "flow.pattern",
          "flow.direction",
          "flow.frequency",
          "flow.swirl",
          "flow.turbulence",
          "paths.reach",
          "paths.strength",
          "paths.data",
          "streams.density",
          "streams.wordGap",
          "highlight.words",
          "highlight.coverage",
          "type.fontSize",
          "canvas.size",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "word-layout",
          "highlight.color",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        id: "word-draw",
        inputs: [
          "word-layout",
          "highlight.color",
          "appearance.background",
          "export.includeBackground",
        ],
        invalidatedBy: [
          "word-layout",
          "highlight.color",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "preview",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Small text can alias without device-pixel-ratio x render-scale backing; mitigated by canvas.renderScale and a scaled backing store, and SVG export keeps true vector text.",
    ],
    layers: [
      {
        content: ["text"],
        exportMode: "included",
        id: "word-texture",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-word-tide-canvas]",
      },
    ],
    performanceRisks: [
      "Word count scales with canvas area over font size squared; mitigated by the cached word-layout pass, batched per-weight fillText draws, and measured by the preview-render and density scenarios.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "vector",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "vector-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM/SVG nodes for thousands of positioned words cause layout and GC pressure; canvas fillText batched by weight is far cheaper while SVG export still provides vector output.",
      "WebGL/WebGPU text requires glyph atlases that compromise crisp text fidelity at arbitrary weights; per-pixel work here is only sparse luminance probes of a decoded ImageData, so Canvas 2D meets budgets without atlas complexity.",
    ],
  },
  rendererWorkload: "vector-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: preview render stays under budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000, maxRenderMs: 2000 },
      expectedObservable:
        "The word texture lays out and draws every placed word within the preview budget at max density.",
      fixture: "max density flow words",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport stays stable",
      browser: true,
      browserTestName: "browser perf: viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable:
        "Panning the canvas keeps frame gaps small because word layout is cached and never re-runs.",
      fixture: "default word tide",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport zoom stays stable under load",
      browser: true,
      browserTestName: "browser perf: viewport zoom stays stable under load",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      expectedObservable:
        "Zooming a dense word texture stays smooth because zoom is a CSS transform, not a relayout.",
      fixture: "max density flow words",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export png stays under budget",
      browser: true,
      browserTestName: "browser perf: export png stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Exporting an 8K PNG of a dense word texture completes within the export budget.",
      fixture: "8k export of dense word texture",
      id: "export-copy",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export svg stays under budget",
      browser: true,
      browserTestName: "browser perf: export svg stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Exporting an SVG with every placed word as a text element completes within the export budget.",
      fixture: "svg export of dense word texture",
      id: "export-svg",
      interaction: "export-copy",
      stressFixture: densityStressFixture,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: mode switch stays responsive",
      browser: true,
      browserTestName: "browser perf: mode switch stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Mode",
      expectedObservable: "Switching between Flow and Dither relays out words within budget.",
      fixture: "default word tide",
      id: "mode-render-change",
      interaction: "control-change",
      target: "mode.render",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: seed drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Seed",
      expectedObservable: "Dragging Seed reshuffles the texture with live feedback.",
      fixture: "default word tide",
      id: "tide-seed-drag",
      interaction: "control-drag",
      target: "tide.seed",
      values: { default: 21, max: 9999, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: randomize stays responsive",
      browser: true,
      browserTestName: "browser perf: randomize stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Randomize",
      expectedObservable: "Clicking Randomize advances the seed within budget.",
      fixture: "default word tide",
      id: "tide-randomize-change",
      interaction: "control-change",
      target: "tide.randomize",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: word list change stays responsive",
      browser: true,
      browserTestName: "browser perf: word list change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Word list",
      expectedObservable:
        "Committing a 6600-token word list re-measures and relays out the texture within budget.",
      fixture: "long word list on large canvas",
      id: "words-list-change",
      interaction: "control-change",
      target: "words.list",
      values: {
        default:
          "OCEAN TIDE CURRENT HARBOR DOCK CARGO SWELL DRIFT NORTH ANCHOR VESSEL PORT",
        max: wordListStressText,
        min: "OCEAN",
      },
      workload: true,
      stressFixture: wordListStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: word order change stays responsive",
      browser: true,
      browserTestName: "browser perf: word order change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Word order",
      expectedObservable: "Switching Sequential/Random relays out tokens within budget.",
      fixture: "default word tide",
      id: "words-order-change",
      interaction: "control-change",
      target: "words.order",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: source image import stays responsive",
      browser: true,
      browserTestName: "browser perf: source image import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      controlLabel: "Source image",
      expectedObservable:
        "Importing a 1920x1080 source photo rasterizes and re-inks the texture within budget.",
      fixture: "1920x1080 source photo",
      id: "source-image-import",
      interaction: "media-import",
      target: "media.sourceImage",
      workload: true,
      stressFixture: sourceMediaWorkloadFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: contrast drag stays responsive",
      browser: true,
      browserTestName: "browser perf: contrast drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Source levels",
      expectedObservable: "Dragging Source levels re-inks sampled words with live feedback.",
      fixture: "source photo loaded",
      id: "source-contrast-drag",
      interaction: "control-drag",
      target: "source.contrast",
      values: { default: 0, max: 100, min: -100 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: invert change stays responsive",
      browser: true,
      browserTestName: "browser perf: invert change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Invert",
      expectedObservable: "Toggling Invert flips ink mapping within budget.",
      fixture: "source photo loaded",
      id: "source-invert-change",
      interaction: "control-change",
      target: "source.invert",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: fade change stays responsive",
      browser: true,
      browserTestName: "browser perf: fade change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Fade",
      expectedObservable: "Toggling Fade switches opacity mapping within budget.",
      fixture: "default word tide",
      id: "ink-fade-change",
      interaction: "control-change",
      target: "ink.fade",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: color count drag stays responsive",
      browser: true,
      browserTestName: "browser perf: color count drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Color count",
      expectedObservable:
        "Dragging Color count to four re-buckets every word color with live feedback.",
      fixture: "four colors on large canvas",
      id: "colors-count-drag",
      interaction: "control-drag",
      target: "colors.count",
      values: { default: 1, max: 4, min: 1 },
      workload: true,
      stressFixture: colorCountStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: sparsity drag stays responsive",
      browser: true,
      browserTestName: "browser perf: sparsity drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Sparsity",
      expectedObservable:
        "Dragging Sparsity to zero keeps every word placed and drawn with live feedback.",
      fixture: "zero sparsity on large canvas",
      id: "ink-sparsity-drag",
      interaction: "control-drag",
      target: "ink.sparsity",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
      stressFixture: sparsityStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: zones enable stays responsive",
      browser: true,
      browserTestName: "browser perf: zones enable stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Zones",
      expectedObservable: "Enabling Tone Zones adds band lookups within budget.",
      fixture: "dither mode",
      id: "zones-enabled-change",
      interaction: "control-change",
      target: "zones.enabled",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zones split drag stays responsive",
      browser: true,
      browserTestName: "browser perf: zones split drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Band split",
      expectedObservable: "Dragging Band split reassigns zone lists with live feedback.",
      fixture: "dither mode with zones",
      id: "zones-split-drag",
      interaction: "control-drag",
      target: "zones.split",
      values: { default: [35, 65], max: [100, 100], min: [0, 0] },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone dark words change stays responsive",
      browser: true,
      browserTestName: "browser perf: zone dark words change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Dark words",
      expectedObservable: "Committing dark-band words relays out the grid within budget.",
      fixture: "dither mode with zones",
      id: "zones-dark-change",
      interaction: "control-change",
      target: "zones.dark",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone mid words change stays responsive",
      browser: true,
      browserTestName: "browser perf: zone mid words change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Mid words",
      expectedObservable: "Committing mid-band words relays out the grid within budget.",
      fixture: "dither mode with zones",
      id: "zones-mid-change",
      interaction: "control-change",
      target: "zones.mid",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: zone light words change stays responsive",
      browser: true,
      browserTestName: "browser perf: zone light words change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Light words",
      expectedObservable: "Committing light-band words relays out the grid within budget.",
      fixture: "dither mode with zones",
      id: "zones-light-change",
      interaction: "control-change",
      target: "zones.light",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: grid gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: grid gap drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Gap",
      expectedObservable:
        "Dragging Gap to zero packs the densest grid while keeping live feedback.",
      fixture: "zero gap dither grid on large canvas",
      id: "grid-gap-drag",
      interaction: "control-drag",
      target: "grid.gap",
      values: { default: 6, max: 60, min: 0 },
      workload: true,
      stressFixture: gridGapStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: grid jitter drag stays responsive",
      browser: true,
      browserTestName: "browser perf: grid jitter drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Jitter",
      expectedObservable: "Dragging Jitter to maximum offsets every slot with live feedback.",
      fixture: "max jitter dither grid on large canvas",
      id: "grid-jitter-drag",
      interaction: "control-drag",
      target: "grid.jitter",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
      stressFixture: gridJitterStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: tone spacing drag stays responsive",
      browser: true,
      browserTestName: "browser perf: tone spacing drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Tone spacing",
      expectedObservable:
        "Dragging Tone spacing rescales darker or lighter zone gaps with live feedback.",
      fixture: "max tone spacing on large canvas",
      id: "grid-spacing-bias-drag",
      interaction: "control-drag",
      target: "grid.spacingBias",
      values: { default: 0, max: 100, min: -100 },
      workload: true,
      stressFixture: gridSpacingBiasStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: spacing range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: spacing range drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Spacing range",
      expectedObservable: "Dragging Spacing range amplifies tone gap strength with live feedback.",
      fixture: "max spacing range on large canvas",
      id: "grid-spacing-range-drag",
      interaction: "control-drag",
      target: "grid.spacingRange",
      values: { default: 50, max: 100, min: 0 },
      workload: true,
      stressFixture: gridSpacingRangeStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: flow pattern change stays responsive",
      browser: true,
      browserTestName: "browser perf: flow pattern change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Pattern",
      expectedObservable: "Switching the field pattern retraces word streams within budget.",
      fixture: "default word tide",
      id: "flow-pattern-change",
      interaction: "control-change",
      target: "flow.pattern",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: direction drag stays responsive",
      browser: true,
      browserTestName: "browser perf: direction drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Direction",
      expectedObservable: "Dragging Direction rotates the field with live feedback.",
      fixture: "default word tide",
      id: "flow-direction-drag",
      interaction: "control-drag",
      target: "flow.direction",
      values: { default: 200, max: 360, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: scale drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Scale",
      expectedObservable:
        "Dragging Scale to maximum packs the tightest field repetition with live feedback.",
      fixture: "max scale flow on large canvas",
      id: "flow-frequency-drag",
      interaction: "control-drag",
      target: "flow.frequency",
      values: { default: 14, max: 40, min: 2 },
      workload: true,
      stressFixture: flowFrequencyStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: swirl drag stays responsive",
      browser: true,
      browserTestName: "browser perf: swirl drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Swirl",
      expectedObservable: "Dragging Swirl bends the field with live feedback.",
      fixture: "default word tide",
      id: "flow-swirl-drag",
      interaction: "control-drag",
      target: "flow.swirl",
      values: { default: 8, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: turbulence drag stays responsive",
      browser: true,
      browserTestName: "browser perf: turbulence drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Turbulence",
      expectedObservable: "Dragging Turbulence distorts the field with live feedback.",
      fixture: "default word tide",
      id: "flow-turbulence-drag",
      interaction: "control-drag",
      target: "flow.turbulence",
      values: { default: 10, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paths edit mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: paths edit mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Edit paths",
      expectedObservable: "Toggling Edit paths shows or hides the overlay within budget.",
      fixture: "default word tide",
      id: "paths-edit-mode-change",
      interaction: "control-change",
      target: "paths.editMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paths reach drag stays responsive",
      browser: true,
      browserTestName: "browser perf: paths reach drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Reach",
      expectedObservable: "Dragging Reach with a path present updates falloff within budget.",
      fixture: "path on large canvas",
      id: "paths-reach-drag",
      interaction: "control-drag",
      target: "paths.reach",
      values: { default: 45, max: 150, min: 0 },
      workload: true,
      stressFixture: pathReachStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: paths strength drag stays responsive",
      browser: true,
      browserTestName: "browser perf: paths strength drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Strength",
      expectedObservable:
        "Dragging Strength with a path present updates field bending within budget.",
      fixture: "path on large canvas",
      id: "paths-strength-drag",
      interaction: "control-drag",
      target: "paths.strength",
      values: { default: 55, max: 100, min: 0 },
      workload: true,
      stressFixture: pathStrengthStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: add path stays responsive",
      browser: true,
      browserTestName: "browser perf: add path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Paths",
      expectedObservable: "Clicking Add path stays responsive.",
      fixture: "default word tide",
      id: "paths-add-path-change",
      interaction: "control-change",
      target: "paths.addPath",
      values: { default: "add-path", max: "add-path", min: "add-path" },
      workload: true,
      stressFixture: pathsAddStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: delete path stays responsive",
      browser: true,
      browserTestName: "browser perf: delete path stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Delete path",
      expectedObservable: "Clicking Delete path stays responsive.",
      fixture: "guide path present",
      id: "paths-delete-path-change",
      interaction: "control-change",
      target: "paths.deletePath",
      values: { default: "delete-path", max: "delete-path", min: "delete-path" },
      workload: true,
      stressFixture: pathsDeleteStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: density drag stays responsive",
      browser: true,
      browserTestName: "browser perf: density drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Density",
      expectedObservable:
        "Dragging Density to maximum packs the most word streams while keeping live feedback.",
      fixture: "max density on large canvas",
      id: "streams-density-drag",
      interaction: "control-drag",
      target: "streams.density",
      values: { default: 55, max: 100, min: 0 },
      workload: true,
      stressFixture: densityStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: word gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: word gap drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Word gap",
      expectedObservable:
        "Dragging Word gap to zero packs the most words per stream with live feedback.",
      fixture: "zero word gap on large canvas",
      id: "streams-word-gap-drag",
      interaction: "control-drag",
      target: "streams.wordGap",
      values: { default: 6, max: 80, min: 0 },
      workload: true,
      stressFixture: wordGapStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: font size drag stays responsive",
      browser: true,
      browserTestName: "browser perf: font size drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Font size",
      expectedObservable:
        "Dragging Font size to 8px packs the most word slots and relays out within budget.",
      fixture: "8px font on large canvas",
      id: "type-font-size-drag",
      interaction: "control-drag",
      target: "type.fontSize",
      values: { default: 18, max: 120, min: 8 },
      workload: true,
      stressFixture: smallFontStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: palette color change stays responsive",
      browser: true,
      browserTestName: "browser perf: palette color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Deep Teal",
      expectedObservable: "Changing Deep Teal repaints mapped words within budget.",
      fixture: "default word tide",
      id: "colors-color1-change",
      interaction: "control-change",
      target: "colors.color1",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: dark slate color change stays responsive",
      browser: true,
      browserTestName: "browser perf: dark slate color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Dark Slate",
      expectedObservable: "Changing Dark Slate repaints the second ink band within budget.",
      fixture: "two palette colors",
      id: "colors-color2-change",
      interaction: "control-change",
      target: "colors.color2",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: capri color change stays responsive",
      browser: true,
      browserTestName: "browser perf: capri color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Capri",
      expectedObservable: "Changing Capri repaints the third ink band within budget.",
      fixture: "three palette colors",
      id: "colors-color3-change",
      interaction: "control-change",
      target: "colors.color3",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: sky blue color change stays responsive",
      browser: true,
      browserTestName: "browser perf: sky blue color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Sky Blue",
      expectedObservable: "Changing Sky Blue repaints the lightest ink band within budget.",
      fixture: "four palette colors",
      id: "colors-color4-change",
      interaction: "control-change",
      target: "colors.color4",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: highlight words change stays responsive",
      browser: true,
      browserTestName: "browser perf: highlight words change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Words",
      expectedObservable: "Committing highlight words re-marks matches within budget.",
      fixture: "default word tide",
      id: "highlight-words-change",
      interaction: "control-change",
      target: "highlight.words",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: highlight color change stays responsive",
      browser: true,
      browserTestName: "browser perf: highlight color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Words",
      expectedObservable: "Changing the marker color repaints highlight rects within budget.",
      fixture: "highlight coverage active",
      id: "highlight-color-change",
      interaction: "control-change",
      target: "highlight.color",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: highlight coverage drag stays responsive",
      browser: true,
      browserTestName: "browser perf: highlight coverage drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Coverage",
      expectedObservable:
        "Dragging Coverage to maximum draws marker rects behind every word with live feedback.",
      fixture: "full highlight coverage on large canvas",
      id: "highlight-coverage-drag",
      interaction: "control-drag",
      target: "highlight.coverage",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
      stressFixture: highlightCoverageStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: mask import stays responsive",
      browser: true,
      browserTestName: "browser perf: mask import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      controlLabel: "Shape Mask",
      expectedObservable:
        "Importing a 1920x1080 alpha shape rebuilds the mask and relays out within budget.",
      fixture: "1920x1080 alpha shape",
      id: "mask-image-import",
      interaction: "media-import",
      target: "media.maskImage",
      workload: true,
      stressFixture: maskMediaWorkloadFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: mask invert change stays responsive",
      browser: true,
      browserTestName: "browser perf: mask invert change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Invert",
      expectedObservable: "Toggling mask Invert rebuilds the alpha map within budget.",
      fixture: "mask loaded",
      id: "mask-invert-change",
      interaction: "control-change",
      target: "mask.invert",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: mask feather drag stays responsive",
      browser: true,
      browserTestName: "browser perf: mask feather drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Feather",
      expectedObservable:
        "Dragging Feather to maximum blurs the full-canvas mask alpha map with live feedback.",
      fixture: "max feather with 1920x1080 mask",
      id: "mask-feather-drag",
      interaction: "control-drag",
      target: "mask.feather",
      values: { default: 0, max: 60, min: 0 },
      workload: true,
      stressFixture: maskFeatherStressFixture,
      workloadFixture: maskMediaWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: include background change stays responsive",
      browser: true,
      browserTestName: "browser perf: include background change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable: "Toggling Include shows or hides the paper background within budget.",
      fixture: "default word tide",
      id: "include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Background",
      expectedObservable: "Changing the background color repaints the fill within budget.",
      fixture: "default word tide",
      id: "background-color-change",
      interaction: "control-change",
      target: "appearance.background",
      uiSelector: "[data-toolcraft-word-tide-canvas]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image format change stays responsive",
      browser: true,
      browserTestName: "browser perf: image format change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Switching export format stays responsive and affects export only.",
      fixture: "default word tide",
      id: "image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image resolution change stays responsive",
      browser: true,
      browserTestName: "browser perf: image resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Preset",
      expectedObservable:
        "Selecting 8K export resolution stays responsive; it scales export size, not the preview.",
      fixture: "8k resolution on large canvas",
      id: "image-resolution-change",
      interaction: "control-change",
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      stressFixture: exportResolutionStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: svg text mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: svg text mode change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "SVG text",
      expectedObservable:
        "Switching SVG text to Outlined paths stays responsive; outline shaping runs at export time.",
      fixture: "svg format on large canvas",
      id: "svg-text-mode-change",
      interaction: "control-change",
      target: "export.svg.text",
      values: { default: "editable", max: "outlines", min: "editable" },
      workload: true,
      stressFixture: svgOutlinesStressFixture,
      workloadFixture: largeCanvasWorkloadFixture,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "words.list",
    "colors.count",
    "ink.sparsity",
    "grid.gap",
    "grid.jitter",
    "grid.spacingBias",
    "grid.spacingRange",
    "paths.reach",
    "paths.strength",
    "paths.addPath",
    "paths.deletePath",
    "streams.density",
    "streams.wordGap",
    "flow.frequency",
    "type.fontSize",
    "highlight.coverage",
    "mask.feather",
    "export.image.resolution",
    "export.svg.text",
  ],
});
